/**
 * IMPOSTOR_DATA.JS
 * Base de datos de palabras y categorías para el juego "El Impostor" (Stahlgraf Games).
 * © 2026 Stahlgraf Games. Todos los derechos reservados.
 * Cada entrada contiene un par de palabras parecidas para soportar tanto:
 *  - Modo Clásico a Ciegas (Inocentes reciben palabraA; Impostor no recibe nada).
 *  - Modo Infiltrado (Inocentes reciben palabraA; Infiltrado recibe palabraB, o viceversa).
 */

const IMPOSTOR_CATEGORIES = {
  comidas: {
    name: "Comidas y Bebidas",
    icon: "🍔",
    color: "#f59e0b",
    desc: "Platos, tragos, postres y comida rápida"
  },
  lugares: {
    name: "Lugares y Viajes",
    icon: "🏖️",
    color: "#06b6d4",
    desc: "Destinos, edificios, transporte y paisajes"
  },
  objetos: {
    name: "Objetos y Tecnología",
    icon: "📱",
    color: "#a855f7",
    desc: "Cosas cotidianas, tecnología y accesorios"
  },
  animales: {
    name: "Animales y Naturaleza",
    icon: "🐾",
    color: "#10b981",
    desc: "Fauna, criaturas y elementos naturales"
  },
  profesiones: {
    name: "Profesiones y Roles",
    icon: "💼",
    color: "#3b82f6",
    desc: "Oficios, trabajos y personajes cotidianos"
  },
  pop_chile: {
    name: "Chile y Cultura Pop",
    icon: "🇨🇱",
    color: "#ef4444",
    desc: "Chilenismos, iconos criollos y cultura popular"
  }
};

const IMPOSTOR_WORD_PAIRS = [
  // ==================== COMIDAS Y BEBIDAS ====================
  { id: 1, categoria: "comidas", palabraA: "Pizza", palabraB: "Hamburguesa" },
  { id: 2, categoria: "comidas", palabraA: "Café", palabraB: "Té" },
  { id: 3, categoria: "comidas", palabraA: "Cerveza", palabraB: "Vino" },
  { id: 4, categoria: "comidas", palabraA: "Helado", palabraB: "Postre de yogur" },
  { id: 5, categoria: "comidas", palabraA: "Sushi", palabraB: "Ceviche" },
  { id: 6, categoria: "comidas", palabraA: "Manzana", palabraB: "Pera" },
  { id: 7, categoria: "comidas", palabraA: "Papas fritas", palabraB: "Nachos" },
  { id: 8, categoria: "comidas", palabraA: "Chocolate", palabraB: "Manjar (Dulce de leche)" },
  { id: 9, categoria: "comidas", palabraA: "Tacos", palabraB: "Burritos" },
  { id: 10, categoria: "comidas", palabraA: "Tallarines", palabraB: "Lasaña" },
  { id: 11, categoria: "comidas", palabraA: "Coca Cola", palabraB: "Pepsi" },
  { id: 12, categoria: "comidas", palabraA: "Sopaipilla", palabraB: "Pan amasado" },
  { id: 13, categoria: "comidas", palabraA: "Arroz con pollo", palabraB: "Paella" },
  { id: 14, categoria: "comidas", palabraA: "Palomitas de maíz", palabraB: "Papas fritas en tarro" },
  { id: 15, categoria: "comidas", palabraA: "Donas", palabraB: "Churros" },
  { id: 16, categoria: "comidas", palabraA: "Jugo de naranja", palabraB: "Limonada" },
  { id: 17, categoria: "comidas", palabraA: "Ketchup", palabraB: "Mostaza" },
  { id: 18, categoria: "comidas", palabraA: "Mayonesa", palabraB: "Salsa tártara" },
  { id: 19, categoria: "comidas", palabraA: "Queso cheddar", palabraB: "Queso gouda" },
  { id: 20, categoria: "comidas", palabraA: "Mantequilla", palabraB: "Margarina" },
  { id: 21, categoria: "comidas", palabraA: "Galletas con chispas", palabraB: "Brownie" },
  { id: 22, categoria: "comidas", palabraA: "Agua mineral", palabraB: "Bebida energética" },
  { id: 23, categoria: "comidas", palabraA: "Waffles", palabraB: "Panqueques" },
  { id: 24, categoria: "comidas", palabraA: "Sandía", palabraB: "Melón" },
  { id: 25, categoria: "comidas", palabraA: "Frutilla", palabraB: "Frambuesa" },

  // ==================== LUGARES Y VIAJES ====================
  { id: 26, categoria: "lugares", palabraA: "Playa", palabraB: "Piscina" },
  { id: 27, categoria: "lugares", palabraA: "Aeropuerto", palabraB: "Terminal de buses" },
  { id: 28, categoria: "lugares", palabraA: "Hospital", palabraB: "Clínica privada" },
  { id: 29, categoria: "lugares", palabraA: "Cine", palabraB: "Teatro" },
  { id: 30, categoria: "lugares", palabraA: "Hotel", palabraB: "Hostal de mochileros" },
  { id: 31, categoria: "lugares", palabraA: "Supermercado", palabraB: "Feria libre" },
  { id: 32, categoria: "lugares", palabraA: "Gimnasio", palabraB: "Cancha de fútbol" },
  { id: 33, categoria: "lugares", palabraA: "Zoológico", palabraB: "Parque safari" },
  { id: 34, categoria: "lugares", palabraA: "Biblioteca", palabraB: "Librería" },
  { id: 35, categoria: "lugares", palabraA: "Museo", palabraB: "Galería de arte" },
  { id: 36, categoria: "lugares", palabraA: "Discoteca", palabraB: "Bar cervecero" },
  { id: 37, categoria: "lugares", palabraA: "Parque de diversiones", palabraB: "Circo" },
  { id: 38, categoria: "lugares", palabraA: "Montaña", palabraB: "Volcán" },
  { id: 39, categoria: "lugares", palabraA: "Bosque", palabraB: "Selva" },
  { id: 40, categoria: "lugares", palabraA: "Desierto", palabraB: "Duna de arena" },
  { id: 41, categoria: "lugares", palabraA: "Castillo", palabraB: "Palacio de gobierno" },
  { id: 42, categoria: "lugares", palabraA: "Iglesia", palabraB: "Catedral" },
  { id: 43, categoria: "lugares", palabraA: "Estación de metro", palabraB: "Paradero de micro" },
  { id: 44, categoria: "lugares", palabraA: "Mall (Centro comercial)", palabraB: "Tienda por departamento" },
  { id: 45, categoria: "lugares", palabraA: "Camping", palabraB: "Cabaña en el bosque" },
  { id: 46, categoria: "lugares", palabraA: "Faro costero", palabraB: "Puerto de barcos" },
  { id: 47, categoria: "lugares", palabraA: "Submarino", palabraB: "Barco crucero" },
  { id: 48, categoria: "lugares", palabraA: "Comisaría", palabraB: "Cárcel" },
  { id: 49, categoria: "lugares", palabraA: "Cementerio", palabraB: "Morgue" },
  { id: 50, categoria: "lugares", palabraA: "Casino de juegos", palabraB: "Sala de bingo" },

  // ==================== OBJETOS Y TECNOLOGÍA ====================
  { id: 51, categoria: "objetos", palabraA: "Teléfono inteligente", palabraB: "Tablet" },
  { id: 52, categoria: "objetos", palabraA: "Guitarra", palabraB: "Ukelele" },
  { id: 53, categoria: "objetos", palabraA: "Lentes de sol", palabraB: "Lentes ópticos" },
  { id: 54, categoria: "objetos", palabraA: "Reloj pulsera", palabraB: "Smartwatch" },
  { id: 55, categoria: "objetos", palabraA: "Zapatillas deportivas", palabraB: "Zapatos de vestir" },
  { id: 56, categoria: "objetos", palabraA: "Audífonos inalámbricos", palabraB: "Parlante Bluetooth" },
  { id: 57, categoria: "objetos", palabraA: "Mochila", palabraB: "Maleta de viaje" },
  { id: 58, categoria: "objetos", palabraA: "Bicicleta", palabraB: "Scooter eléctrico" },
  { id: 59, categoria: "objetos", palabraA: "Auto", palabraB: "Camioneta" },
  { id: 60, categoria: "objetos", palabraA: "Microondas", palabraB: "Horno eléctrico" },
  { id: 61, categoria: "objetos", palabraA: "Refrigerador", palabraB: "Congelador" },
  { id: 62, categoria: "objetos", palabraA: "Cepillo de dientes", palabraB: "Hilo dental" },
  { id: 63, categoria: "objetos", palabraA: "Shampoo", palabraB: "Jabón líquido" },
  { id: 64, categoria: "objetos", palabraA: "Paraguas", palabraB: "Impermeable" },
  { id: 65, categoria: "objetos", palabraA: "Libro de papel", palabraB: "Lector electrónico (Kindle)" },
  { id: 66, categoria: "objetos", palabraA: "Cámara fotográfica", palabraB: "GoPro" },
  { id: 67, categoria: "objetos", palabraA: "Linterna", palabraB: "Vela" },
  { id: 68, categoria: "objetos", palabraA: "Almohada", palabraB: "Cojín de sofá" },
  { id: 69, categoria: "objetos", palabraA: "Taza de cerámica", palabraB: "Vaso de vidrio" },
  { id: 70, categoria: "objetos", palabraA: "Cuchara", palabraB: "Tenedor" },
  { id: 71, categoria: "objetos", palabraA: "Plancha de ropa", palabraB: "Secador de pelo" },
  { id: 72, categoria: "objetos", palabraA: "Moneda", palabraB: "Billete" },
  { id: 73, categoria: "objetos", palabraA: "Billetera", palabraB: "Monedero" },
  { id: 74, categoria: "objetos", palabraA: "Control remoto", palabraB: "Mando de PlayStation" },
  { id: 75, categoria: "objetos", palabraA: "Colchón inflable", palabraB: "Saco de dormir" },

  // ==================== ANIMALES Y NATURALEZA ====================
  { id: 76, categoria: "animales", palabraA: "Perro", palabraB: "Lobo" },
  { id: 77, categoria: "animales", palabraA: "Gato doméstico", palabraB: "Tigre" },
  { id: 78, categoria: "animales", palabraA: "Delfín", palabraB: "Tiburón" },
  { id: 79, categoria: "animales", palabraA: "Caballo", palabraB: "Burro" },
  { id: 80, categoria: "animales", palabraA: "León", palabraB: "Leopardo" },
  { id: 81, categoria: "animales", palabraA: "Águila", palabraB: "Halcón" },
  { id: 82, categoria: "animales", palabraA: "Pingüino", palabraB: "Foca" },
  { id: 83, categoria: "animales", palabraA: "Cocodrilo", palabraB: "Caimán" },
  { id: 84, categoria: "animales", palabraA: "Oso polar", palabraB: "Oso pardo" },
  { id: 85, categoria: "animales", palabraA: "Vaca", palabraB: "Oveja" },
  { id: 86, categoria: "animales", palabraA: "Rata", palabraB: "Hámster" },
  { id: 87, categoria: "animales", palabraA: "Abeja", palabraB: "Avispa" },
  { id: 88, categoria: "animales", palabraA: "Mariposa", palabraB: "Polilla" },
  { id: 89, categoria: "animales", palabraA: "Loro", palabraB: "Tucán" },
  { id: 90, categoria: "animales", palabraA: "Serpiente", palabraB: "Lombriz" },
  { id: 91, categoria: "animales", palabraA: "Pulpo", palabraB: "Calamar" },
  { id: 92, categoria: "animales", palabraA: "Ballena", palabraB: "Orca" },
  { id: 93, categoria: "animales", palabraA: "Elefante", palabraB: "Rinoceronte" },
  { id: 94, categoria: "animales", palabraA: "Jirafa", palabraB: "Cebra" },
  { id: 95, categoria: "animales", palabraA: "Canguro", palabraB: "Koala" },
  { id: 96, categoria: "animales", palabraA: "Pato", palabraB: "Ganso" },
  { id: 97, categoria: "animales", palabraA: "Gallina", palabraB: "Pavo" },
  { id: 98, categoria: "animales", palabraA: "Araña", palabraB: "Escorpión" },
  { id: 99, categoria: "animales", palabraA: "Conejo", palabraB: "Liebre" },
  { id: 100, categoria: "animales", palabraA: "Cóndor", palabraB: "Buitre" },

  // ==================== PROFESIONES Y ROLES ====================
  { id: 101, categoria: "profesiones", palabraA: "Médico cirujano", palabraB: "Enfermero" },
  { id: 102, categoria: "profesiones", palabraA: "Profesor de colegio", palabraB: "Profesor universitario" },
  { id: 103, categoria: "profesiones", palabraA: "Policía", palabraB: "Detective privado" },
  { id: 104, categoria: "profesiones", palabraA: "Bombero", palabraB: "Paramédico" },
  { id: 105, categoria: "profesiones", palabraA: "Piloto de avión", palabraB: "Azafata (Tripulante)" },
  { id: 106, categoria: "profesiones", palabraA: "Chef de restaurante", palabraB: "Mesero" },
  { id: 107, categoria: "profesiones", palabraA: "Abogado", palabraB: "Juez del tribunal" },
  { id: 108, categoria: "profesiones", palabraA: "Dentista", palabraB: "Oftalmólogo" },
  { id: 109, categoria: "profesiones", palabraA: "Veterinario", palabraB: "Entrenador canino" },
  { id: 110, categoria: "profesiones", palabraA: "Peluquero (Barbero)", palabraB: "Maquillador" },
  { id: 111, categoria: "profesiones", palabraA: "Fotógrafo", palabraB: "Camarógrafo" },
  { id: 112, categoria: "profesiones", palabraA: "Futbolista profesional", palabraB: "Árbitro de fútbol" },
  { id: 113, categoria: "profesiones", palabraA: "Actor de cine", palabraB: "Director de cine" },
  { id: 114, categoria: "profesiones", palabraA: "Cantante de banda", palabraB: "Baterista" },
  { id: 115, categoria: "profesiones", palabraA: "Arquitecto", palabraB: "Albañil constructor" },
  { id: 116, categoria: "profesiones", palabraA: "Astronauta", palabraB: "Astrónomo" },
  { id: 117, categoria: "profesiones", palabraA: "Taxista", palabraB: "Chofer de micro" },
  { id: 118, categoria: "profesiones", palabraA: "Cajero de banco", palabraB: "Guardia de seguridad" },
  { id: 119, categoria: "profesiones", palabraA: "Mago de fiesta", palabraB: "Payaso de circo" },
  { id: 120, categoria: "profesiones", palabraA: "Pintor artístico", palabraB: "Escultor" },
  { id: 121, categoria: "profesiones", palabraA: "Mecánico de autos", palabraB: "Electricista" },
  { id: 122, categoria: "profesiones", palabraA: "Periodista de TV", palabraB: "Youtuber famoso" },
  { id: 123, categoria: "profesiones", palabraA: "Panadero", palabraB: "Pastelero" },
  { id: 124, categoria: "profesiones", palabraA: "Pescador artesanal", palabraB: "Buzo táctico" },
  { id: 125, categoria: "profesiones", palabraA: "Político", palabraB: "Diplomático" },

  // ==================== CHILE Y CULTURA POP ====================
  { id: 126, categoria: "pop_chile", palabraA: "Completo Italiano", palabraB: "Chacarero" },
  { id: 127, categoria: "pop_chile", palabraA: "Piscola blanca", palabraB: "Piscola negra" },
  { id: 128, categoria: "pop_chile", palabraA: "Terremoto (Trago)", palabraB: "Borgoña" },
  { id: 129, categoria: "pop_chile", palabraA: "Asado familiar", palabraB: "Anticucho dieciochero" },
  { id: 130, categoria: "pop_chile", palabraA: "Metro de Santiago", palabraB: "Micro Red (Transantiago)" },
  { id: 131, categoria: "pop_chile", palabraA: "Viña del Mar", palabraB: "Valparaíso" },
  { id: 132, categoria: "pop_chile", palabraA: "Colo-Colo", palabraB: "Universidad de Chile" },
  { id: 133, categoria: "pop_chile", palabraA: "Alexis Sánchez", palabraB: "Arturo Vidal" },
  { id: 134, categoria: "pop_chile", palabraA: "Don Francisco", palabraB: "Felipe Camiroaga" },
  { id: 135, categoria: "pop_chile", palabraA: "Fonda dieciochera", palabraB: "Ramada tradicional" },
  { id: 136, categoria: "pop_chile", palabraA: "Cazuela de vacuno", palabraB: "Charquicán" },
  { id: 137, categoria: "pop_chile", palabraA: "Empanada de pino", palabraB: "Empanada de queso" },
  { id: 138, categoria: "pop_chile", palabraA: "Pudahuel (Aeropuerto)", palabraB: "Terminal San Borja" },
  { id: 139, categoria: "pop_chile", palabraA: "Fantasilandia", palabraB: "Mampato" },
  { id: 140, categoria: "pop_chile", palabraA: "La Teletón", palabraB: "Festival de Viña" },
  { id: 141, categoria: "pop_chile", palabraA: "31 Minutos", palabraB: "Cachureos" },
  { id: 142, categoria: "pop_chile", palabraA: "Cueca chilena", palabraB: "Cumbia villera" },
  { id: 143, categoria: "pop_chile", palabraA: "Condorito", palabraB: "Yayita" },
  { id: 144, categoria: "pop_chile", palabraA: "Chupalla huasa", palabraB: "Gorro chilote" },
  { id: 145, categoria: "pop_chile", palabraA: "Costanera Center", palabraB: "Torre Entel" },
  { id: 146, categoria: "pop_chile", palabraA: "Bebida Pap", palabraB: "Bebida Bilz" },
  { id: 147, categoria: "pop_chile", palabraA: "Negrita (Chokita)", palabraB: "Super 8" },
  { id: 148, categoria: "pop_chile", palabraA: "TikTok", palabraB: "Instagram Reels" },
  { id: 149, categoria: "pop_chile", palabraA: "Netflix", palabraB: "YouTube" },
  { id: 150, categoria: "pop_chile", palabraA: "Batman", palabraB: "Spiderman" }
];
