/**
 * BASE DE DATOS DE PERSONAJES: ¿QUIÉN SOY?
 * © 2026 Stahlgraf Games. Todos los derechos reservados.
 * =======================================
 * Categorías:
 * - chile: Famosos, virales, cultura pop y TV chilena
 * - cine: Personajes de películas, series y ficción
 * - infantil: Dibujos animados, caricaturas y videojuegos
 * - historia: Grandes figuras históricas y científicos
 * - musica: Estrellas de la música y cantantes mundiales
 * - deportes: Leyendas del deporte mundial y chileno
 */

const QUIEN_SOY_CATEGORIES = {
  chile: {
    id: 'chile',
    name: 'Chile Pop & Virales',
    icon: '🇨🇱',
    color: '#ef4444',
    desc: 'Farándula, virales, TV, internet y cultura pop chilena'
  },
  cine: {
    id: 'cine',
    name: 'Cine & Series',
    icon: '🎬',
    color: '#8b5cf6',
    desc: 'Héroes, villanos y leyendas del cine y series'
  },
  infantil: {
    id: 'infantil',
    name: 'Animación & Juegos',
    icon: '🧸',
    color: '#06b6d4',
    desc: 'Dibujos animados, caricaturas, Disney y videojuegos'
  },
  historia: {
    id: 'historia',
    name: 'Historia & Ciencia',
    icon: '🏛️',
    color: '#f59e0b',
    desc: 'Científicos, líderes, próceres y leyendas históricas'
  },
  musica: {
    id: 'musica',
    name: 'Música & Cantantes',
    icon: '🎵',
    color: '#ec4899',
    desc: 'Íconos mundiales del pop, rock, reggaetón y baladas'
  },
  deportes: {
    id: 'deportes',
    name: 'Deportes',
    icon: '⚽',
    color: '#10b981',
    desc: 'Astros del fútbol, tenis, básquetbol y atletismo'
  }
};

const QUIEN_SOY_PERSONAJES = [
  // ==================== CHILE ====================
  { nombre: "Pedro Pascal", categoria: "chile", pista: "Actor chileno estrella de Hollywood" },
  { nombre: "Felipe Camiroaga", categoria: "chile", pista: "El querido 'Halcón de Chicureo'" },
  { nombre: "Don Francisco", categoria: "chile", pista: "Animador legendario de Sábado Gigante y Teletón" },
  { nombre: "Mon Laferte", categoria: "chile", pista: "Cantante chilena ganadora de Grammys" },
  { nombre: "Arturo Vidal", categoria: "chile", pista: "El 'King', mediocampista de la Generación Dorada" },
  { nombre: "Alexis Sánchez", categoria: "chile", pista: "El 'Niño Maravilla' de Tocopilla" },
  { nombre: "Stefan Kramer", categoria: "chile", pista: "El hombre de las mil caras e imitaciones" },
  { nombre: "Bombo Fica", categoria: "chile", pista: "Humorista vestido de blanco impecable" },
  { nombre: "Coco Legrand", categoria: "chile", pista: "Maestro del humor y el monólogo chileno" },
  { nombre: "Pancho Saavedra", categoria: "chile", pista: "Animador de 'Lugares que Hablan' con risa contagiosa" },
  { nombre: "Julio César Rodríguez", categoria: "chile", pista: "Animador de matinales y 'La Junta'" },
  { nombre: "Kenita Larraín", categoria: "chile", pista: "Modelo, numeróloga y reina de la farándula" },
  { nombre: "Anita Alvarado", categoria: "chile", pista: "La famosa 'Geisha chilena'" },
  { nombre: "Marcelo 'Chino' Ríos", categoria: "chile", pista: "Ex número 1 del mundo en tenis" },
  { nombre: "El Zafrada", categoria: "chile", pista: "Niño viral del terremoto 2010 ('las zafradas')" },
  { nombre: "El Tarro", categoria: "chile", pista: "Niño viral que saltaba obstáculos en bicicleta" },
  { nombre: "Chimuelo", categoria: "chile", pista: "El periquito del entierro más viral de Chile" },
  { nombre: "Chupete Suazo", categoria: "chile", pista: "Goleador del planeta con la cabeza rapada" },
  { nombre: "Gary Medel", categoria: "chile", pista: "El 'Pitbull' aguerrido de la selección" },
  { nombre: "Jorge Valdivia", categoria: "chile", pista: "El 'Mago' del fútbol chileno" },
  { nombre: "Tonka Tomicic", categoria: "chile", pista: "Famosa conductora de televisión y modelo" },
  { nombre: "Cecilia Bolocco", categoria: "chile", pista: "Miss Universo chilena y diseñadora" },
  { nombre: "Iván Zamorano", categoria: "chile", pista: "Bam Bam, goleador del Real Madrid e Inter" },
  { nombre: "Marcelo Salas", categoria: "chile", pista: "El 'Matador', ídolo de la U y la Lazio" },
  { nombre: "Tulio Triviño", categoria: "chile", pista: "Conductor estrella del noticiero 31 Minutos" },
  { nombre: "Juan Carlos Bodoque", categoria: "chile", pista: "Conejo rojo de la Nota Verde de 31 Minutos" },
  { nombre: "Profesor Rossa", categoria: "chile", pista: "Personaje con peluca rosada y videos educativos" },
  { nombre: "Guru Guru", categoria: "chile", pista: "Paloma amiga del Profesor Rossa que habla con 'G'" },
  { nombre: "Compadre Moncho", categoria: "chile", pista: "Personaje de Los Venegas que recorre Santiago" },
  { nombre: "Marcianeke", categoria: "chile", pista: "Cantante urbano de Talca con voz ronca ('Dímelo Má')" },
  { nombre: "Polimá Westcoast", categoria: "chile", pista: "Cantante de música urbana ('Ultra Solo')" },
  { nombre: "Pablo Chill-E", categoria: "chile", pista: "Líder de la Shishi Gang y trap chileno" },
  { nombre: "Fabrizio Copano", categoria: "chile", pista: "Comediante triunfador en Viña y EE.UU." },
  { nombre: "Edo Caroe", categoria: "chile", pista: "Mago y comediante de humor negro" },
  { nombre: "Alison Mandel", categoria: "chile", pista: "Comediante chilena de stand-up" },
  { nombre: "Sergio Freire", categoria: "chile", pista: "Comediante recordado por 'El Club de la Comedia'" },
  { nombre: "Jorge Alís", categoria: "chile", pista: "El 'Argentino QL' del humor en Chile" },
  { nombre: "Guatón Salinas", categoria: "chile", pista: "Comediante conocido por 'Chopico' y 'Ratoncitos'" },
  { nombre: "Pollo Fuentes", categoria: "chile", pista: "Cantante ídolo de la Nueva Ola chilena" },
  { nombre: "Zalo Reyes", categoria: "chile", pista: "El 'Gorrión de Conchalí'" },
  { nombre: "Christiane Endler", categoria: "chile", pista: "Mejor arquera del mundo y capitana de la Roja" },
  { nombre: "Tomás González", categoria: "chile", pista: "Gimnasta olímpico récord de Chile" },

  // ==================== CINE & SERIES ====================
  { nombre: "Harry Potter", categoria: "cine", pista: "El niño mago con la cicatriz de rayo" },
  { nombre: "Darth Vader", categoria: "cine", pista: "Lord Sith con máscara negra y respiración pesada" },
  { nombre: "Batman", categoria: "cine", pista: "El caballero de la noche de Gotham City" },
  { nombre: "Spider-Man", categoria: "cine", pista: "El superhéroe arácnido Peter Parker" },
  { nombre: "Jack Sparrow", categoria: "cine", pista: "Capitán pirata excéntrico del Perla Negra" },
  { nombre: "James Bond", categoria: "cine", pista: "El agente secreto 007 con licencia para matar" },
  { nombre: "Sherlock Holmes", categoria: "cine", pista: "Detective inglés maestro de la deducción" },
  { nombre: "Walter White", categoria: "cine", pista: "Profesor de química convertido en Heisenberg" },
  { nombre: "Joker / Guasón", categoria: "cine", pista: "El payaso príncipe del crimen y rival de Batman" },
  { nombre: "Thanos", categoria: "cine", pista: "El titán loco que chasqueó los dedos con el Guantelete" },
  { nombre: "Hermione Granger", categoria: "cine", pista: "La alumna más brillante de Gryffindor" },
  { nombre: "Neo (Matrix)", categoria: "cine", pista: "El Elegido que esquiva balas y viste de negro" },
  { nombre: "Indiana Jones", categoria: "cine", pista: "Arqueólogo con sombrero fedora y látigo" },
  { nombre: "Barbie", categoria: "cine", pista: "La muñeca más famosa del mundo que vive en Barbieland" },
  { nombre: "Capitán América", categoria: "cine", pista: "El primer vengador con escudo de vibranium" },
  { nombre: "Iron Man", categoria: "cine", pista: "Tony Stark, genio millonario con armadura de alta tecnología" },
  { nombre: "Gandalf", categoria: "cine", pista: "El poderoso mago gris y blanco de El Señor de los Anillos" },
  { nombre: "Frodo Bolsón", categoria: "cine", pista: "El hobbit que llevó el Anillo Único a Mordor" },
  { nombre: "John Wick", categoria: "cine", pista: "Asesino letal que busca venganza por su perro" },
  { nombre: "Terminator", categoria: "cine", pista: "Cyborg enviado del futuro con frase 'Hasta la vista, baby'" },
  { nombre: "Katniss Everdeen", categoria: "cine", pista: "La 'Chica en Llamas' de Los Juegos del Hambre" },
  { nombre: "Michael Corleone", categoria: "cine", pista: "Hijo de Don Vito y líder de El Padrino" },
  { nombre: "Hannibal Lecter", categoria: "cine", pista: "Brillante psiquiatra y caníbal de El Silencio de los Inocentes" },
  { nombre: "Merlina Addams", categoria: "cine", pista: "Hija gótica de los Locos Addams que viste de negro" },
  { nombre: "Yoda", categoria: "cine", pista: "Pequeño maestro Jedi verde de gran sabiduría" },
  { nombre: "Gollum", categoria: "cine", pista: "Criatura obsesionada con 'mi tesoro'" },
  { nombre: "Luke Skywalker", categoria: "cine", pista: "Jedi que destruyó la primera Estrella de la Muerte" },
  { nombre: "Mujer Maravilla", categoria: "cine", pista: "Princesa amazona con lazo de la verdad" },
  { nombre: "Lord Voldemort", categoria: "cine", pista: "El Señor Tenebroso 'que no debe ser nombrado'" },
  { nombre: "Forrest Gump", categoria: "cine", pista: "Hombre noble que decía 'La vida es como una caja de chocolates'" },
  { nombre: "El Profesor (La Casa de Papel)", categoria: "cine", pista: "Mente maestra detrás del robo a la Casa de la Moneda" },
  { nombre: "Eleven (Stranger Things)", categoria: "cine", pista: "Niña con poderes telequinéticos que ama los waffles" },
  { nombre: "Thomas Shelby", categoria: "cine", pista: "Líder de la banda Peaky Blinders de Birmingham" },
  { nombre: "Willy Wonka", categoria: "cine", pista: "Excéntrico dueño de la fábrica de chocolates" },
  { nombre: "El Zorro", categoria: "cine", pista: "Héroe enmascarado con espada que firma con una Z" },
  { nombre: "Drácula", categoria: "cine", pista: "El conde vampiro más famoso de Transilvania" },
  { nombre: "Frankenstein", categoria: "cine", pista: "Monstruo creado con piezas humanas y electricidad" },
  { nombre: "Groot", categoria: "cine", pista: "Árbol alienígena que solo dice 'Yo soy Groot'" },

  // ==================== ANIMACIÓN & JUEGOS ====================
  { nombre: "Mickey Mouse", categoria: "infantil", pista: "El ratón insignia de Disney con orejas redondas" },
  { nombre: "Bob Esponja", categoria: "infantil", pista: "Vive en una piña debajo del mar en Fondo de Bikini" },
  { nombre: "Pikachu", categoria: "infantil", pista: "Ratón eléctrico amarillo compañero de Ash" },
  { nombre: "Mario Bros", categoria: "infantil", pista: "Fontanero de gorra roja que rescata a la Princesa Peach" },
  { nombre: "Goku", categoria: "infantil", pista: "Guerrero Saiyajin que hace el Kamehameha" },
  { nombre: "Bugs Bunny", categoria: "infantil", pista: "Conejo de Looney Tunes que come zanahoria ('¿Qué hay de nuevo, viejo?')" },
  { nombre: "Homero Simpson", categoria: "infantil", pista: "Amante de las rosquillas y la cerveza Duff ('D'oh!')" },
  { nombre: "Bart Simpson", categoria: "infantil", pista: "Niño travieso de patineta ('Ay caramba')" },
  { nombre: "Peppa Pig", categoria: "infantil", pista: "Cerdita británica que ama saltar en charcos de lodo" },
  { nombre: "Woody", categoria: "infantil", pista: "Vaquero de juguete líder del cuarto de Andy" },
  { nombre: "Buzz Lightyear", categoria: "infantil", pista: "Guardián espacial que vuela 'Al infinito y más allá'" },
  { nombre: "Elsa (Frozen)", categoria: "infantil", pista: "Reina del hielo que canta 'Libre Soy'" },
  { nombre: "Sonic el Erizo", categoria: "infantil", pista: "Erizo azul ultra rápido que recolecta anillos dorados" },
  { nombre: "Scooby-Doo", categoria: "infantil", pista: "Perro gran danés miedoso que resuelve misterios" },
  { nombre: "Garfield", categoria: "infantil", pista: "Gato naranja perezoso que odia los lunes y ama la lasaña" },
  { nombre: "Tom y Jerry", categoria: "infantil", pista: "El gato y el ratón más famosos de la animación" },
  { nombre: "Pantera Rosa", categoria: "infantil", pista: "Felino elegante y silencioso con música de saxofón" },
  { nombre: "Bob Patiño", categoria: "infantil", pista: "Villano de pelo de palmera que odia a Bart y pisa rastrillos" },
  { nombre: "Pato Donald", categoria: "infantil", pista: "Pato de traje marinero y voz ininteligible de Disney" },
  { nombre: "Patricio Estrella", categoria: "infantil", pista: "Estrella de mar rosada y mejor amigo de Bob Esponja" },
  { nombre: "Calamardo", categoria: "infantil", pista: "Pulpo amargado que toca el clarinete" },
  { nombre: "Shrek", categoria: "infantil", pista: "Ogro verde que vive en un pantano" },
  { nombre: "Burro (Shrek)", categoria: "infantil", pista: "Asno parlanchín que hace waffles y molesta a Shrek" },
  { nombre: "Simba", categoria: "infantil", pista: "Leoncito que aprende el 'Hakuna Matata'" },
  { nombre: "Popeye el Marino", categoria: "infantil", pista: "Marinero con pipa que saca músculos comiendo espinacas" },
  { nombre: "Winnie Pooh", categoria: "infantil", pista: "Osito amarillo fanático de los tarros de miel" },
  { nombre: "Minions", categoria: "infantil", pista: "Pequeños seres amarillos con gafas que aman las bananas" },
  { nombre: "Link (Zelda)", categoria: "infantil", pista: "Héroe de túnica verde que empuña la Espada Maestra" },
  { nombre: "Luigi", categoria: "infantil", pista: "Hermano de Mario, más alto y vestido de verde" },
  { nombre: "Bowser", categoria: "infantil", pista: "Tortuga gigante con caparazón de púas que lanza fuego" },
  { nombre: "Naruto Uzumaki", categoria: "infantil", pista: "Ninja rubio de Konoha que ama el ramen" },
  { nombre: "Vegeta", categoria: "infantil", pista: "Orgulloso príncipe de los Saiyajin" },
  { nombre: "Donkey Kong", categoria: "infantil", pista: "Gorila con corbata roja que lanza barriles" },
  { nombre: "Pac-Man", categoria: "infantil", pista: "Círculo amarillo que come puntos y huye de fantasmas" },

  // ==================== HISTORIA & CIENCIA ====================
  { nombre: "Albert Einstein", categoria: "historia", pista: "Físico de pelo alborotado que postuló la Teoría de la Relatividad" },
  { nombre: "Cleopatra", categoria: "historia", pista: "Última reina del Antiguo Egipto" },
  { nombre: "Cristóbal Colón", categoria: "historia", pista: "Navegante genovés que llegó a América en 1492" },
  { nombre: "Leonardo da Vinci", categoria: "historia", pista: "Pintor de la Mona Lisa e inventor renacentista" },
  { nombre: "Napoleón Bonaparte", categoria: "historia", pista: "Emperador francés famoso por su sombrero y campañas militares" },
  { nombre: "Julio César", categoria: "historia", pista: "Líder militar y dictador de la Antigua Roma ('Veni, vidi, vici')" },
  { nombre: "Isaac Newton", categoria: "historia", pista: "Científico que descubrió la gravedad con una manzana" },
  { nombre: "Marie Curie", categoria: "historia", pista: "Pionera de la radiactividad y doble ganadora del Premio Nobel" },
  { nombre: "Charles Darwin", categoria: "historia", pista: "Naturalista que propuso la Teoría de la Evolución de las Especies" },
  { nombre: "Bernardo O'Higgins", categoria: "historia", pista: "Padre de la Patria y Director Supremo de Chile" },
  { nombre: "Arturo Prat", categoria: "historia", pista: "Héroe naval del Combate Naval de Iquique" },
  { nombre: "Pablo Neruda", categoria: "historia", pista: "Poeta chileno ganador del Premio Nobel de Literatura" },
  { nombre: "Gabriela Mistral", categoria: "historia", pista: "Primera escritora latinoamericana en ganar el Premio Nobel" },
  { nombre: "Manuel Rodríguez", categoria: "historia", pista: "El guerrillero y héroe popular de la Independencia de Chile" },
  { nombre: "Mahatma Gandhi", categoria: "historia", pista: "Líder pacifista que liberó a la India sin violencia" },
  { nombre: "Nelson Mandela", categoria: "historia", pista: "Líder sudafricano que venció el Apartheid tras 27 años en prisión" },
  { nombre: "Abraham Lincoln", categoria: "historia", pista: "Presidente de EE.UU. que abolió la esclavitud y usaba sombrero de copa" },
  { nombre: "Juana de Arco", categoria: "historia", pista: "Joven heroína y santa francesa de la Guerra de los Cien Años" },
  { nombre: "Alejandro Magno", categoria: "historia", pista: "Rey de Macedonia que conquistó casi todo el mundo conocido" },
  { nombre: "Galileo Galilei", categoria: "historia", pista: "Astrónomo que defendió que la Tierra gira alrededor del Sol" },
  { nombre: "William Shakespeare", categoria: "historia", pista: "Dramaturgo inglés autor de Romeo y Julieta y Hamlet" },
  { nombre: "Mozart", categoria: "historia", pista: "Genio y niño prodigio de la música clásica europea" },
  { nombre: "Beethoven", categoria: "historia", pista: "Compositor que creó la Novena Sinfonía estando sordo" },
  { nombre: "Steve Jobs", categoria: "historia", pista: "Cofundador de Apple creador del iPhone y Mac" },
  { nombre: "Thomas Edison", categoria: "historia", pista: "Prolífico inventor de la bombilla eléctrica y el fonógrafo" },
  { nombre: "Nikola Tesla", categoria: "historia", pista: "Genio de la corriente alterna y la electricidad" },
  { nombre: "Stephen Hawking", categoria: "historia", pista: "Físico teórico en silla de ruedas que estudió los agujeros negros" },
  { nombre: "Martin Luther King", categoria: "historia", pista: "Líder por los derechos civiles que dijo 'Yo tengo un sueño'" },

  // ==================== MÚSICA & CANTANTES ====================
  { nombre: "Michael Jackson", categoria: "musica", pista: "El 'Rey del Pop' creador de la caminata lunar (Moonwalk)" },
  { nombre: "Freddie Mercury", categoria: "musica", pista: "Líder carismático y vocalista de la banda Queen" },
  { nombre: "Shakira", categoria: "musica", pista: "Cantante colombiana famosa por el movimiento de caderas y el Waka Waka" },
  { nombre: "Bad Bunny", categoria: "musica", pista: "El 'Conejo Malo', superestrella puertorriqueña del trap y reggaetón" },
  { nombre: "Taylor Swift", categoria: "musica", pista: "Superestrella global del pop y country con el Eras Tour" },
  { nombre: "Elvis Presley", categoria: "musica", pista: "El 'Rey del Rock and Roll' de tupé y trajes brillantes" },
  { nombre: "Madonna", categoria: "musica", pista: "La indiscutible 'Reina del Pop'" },
  { nombre: "Justin Bieber", categoria: "musica", pista: "Cantante canadiense descubierto en YouTube ('Baby')" },
  { nombre: "Beyoncé", categoria: "musica", pista: "La 'Queen Bey', cantante y reina del R&B" },
  { nombre: "Eminem", categoria: "musica", pista: "El rapero blanco más exitoso de la historia ('Lose Yourself')" },
  { nombre: "Luis Miguel", categoria: "musica", pista: "El 'Sol de México' con voz inigualable" },
  { nombre: "Daddy Yankee", categoria: "musica", pista: "El 'Big Boss' y rey de la Gasolina y el reggaetón" },
  { nombre: "Rosalía", categoria: "musica", pista: "Cantante española creadora de la 'Motomami'" },
  { nombre: "Bob Marley", categoria: "musica", pista: "Ícono jamaiquino y leyenda del reggae con rastas" },
  { nombre: "John Lennon", categoria: "musica", pista: "Miembro de The Beatles y compositor de 'Imagine'" },
  { nombre: "Kurt Cobain", categoria: "musica", pista: "Líder de Nirvana y voz del movimiento grunge" },
  { nombre: "Dua Lipa", categoria: "musica", pista: "Cantante británica de pop disco ('Levitating')" },
  { nombre: "Billie Eilish", categoria: "musica", pista: "Joven cantante de voz susurrada y canciones melancólicas" },
  { nombre: "Lady Gaga", categoria: "musica", pista: "Cantante de 'Bad Romance' conocida por sus trajes extravagantes" },
  { nombre: "Adele", categoria: "musica", pista: "Cantante británica de baladas conmovedoras ('Rolling in the Deep')" },
  { nombre: "Elton John", categoria: "musica", pista: "Pianista y cantante británico con lentes coloridos extravagantes" },
  { nombre: "Bruno Mars", categoria: "musica", pista: "Cantante y bailarín de funk y pop ('Uptown Funk')" },
  { nombre: "Ricky Martin", categoria: "musica", pista: "Astro boricua de 'Livin' la Vida Loca'" },
  { nombre: "Chayanne", categoria: "musica", pista: "El amor platónico de todas las mamás de Latinoamérica" },
  { nombre: "Karol G", categoria: "musica", pista: "La 'Bichota' colombiana del reggaetón" },
  { nombre: "Drake", categoria: "musica", pista: "Rapero canadiense de Hotline Bling y récords de streaming" },
  { nombre: "Celia Cruz", categoria: "musica", pista: "La 'Reina de la Salsa' con su grito '¡Azúcar!'" },
  { nombre: "Rihanna", categoria: "musica", pista: "Cantante de Barbados de 'Umbrella' y empresaria de cosméticos" },

  // ==================== DEPORTES ====================
  { nombre: "Lionel Messi", categoria: "deportes", pista: "Astro argentino con 8 Balones de Oro y campeón del mundo" },
  { nombre: "Cristiano Ronaldo", categoria: "deportes", pista: "CR7, el goleador histórico portugués con su grito '¡Siuuu!'" },
  { nombre: "Diego Maradona", categoria: "deportes", pista: "El 'Pelusa', autor de la Mano de Dios y el Gol del Siglo" },
  { nombre: "Pelé", categoria: "deportes", pista: "El 'Rey del Fútbol', tres veces campeón mundial con Brasil" },
  { nombre: "Michael Jordan", categoria: "deportes", pista: "El legendario número 23 de los Chicago Bulls" },
  { nombre: "Usain Bolt", categoria: "deportes", pista: "El hombre más rápido de la historia en los 100 metros planos" },
  { nombre: "Roger Federer", categoria: "deportes", pista: "Maestro suizo de tenis con elegancia pura" },
  { nombre: "Rafael Nadal", categoria: "deportes", pista: "El rey indiscutido de la tierra batida en Roland Garros" },
  { nombre: "Novak Djokovic", categoria: "deportes", pista: "Tenista serbio con récord de títulos de Grand Slam" },
  { nombre: "Mike Tyson", categoria: "deportes", pista: "Pugilista temido por su pegada fulminante y mordida de oreja" },
  { nombre: "Muhammad Ali", categoria: "deportes", pista: "El boxeador más grande de todos los tiempos ('Vuela como mariposa...')" },
  { nombre: "Kobe Bryant", categoria: "deportes", pista: "La 'Mamba Negra' de Los Angeles Lakers" },
  { nombre: "LeBron James", categoria: "deportes", pista: "El 'Rey' LeBron, máximo anotador histórico de la NBA" },
  { nombre: "Serena Williams", categoria: "deportes", pista: "La reina más dominante del tenis femenino mundial" },
  { nombre: "Neymar Jr", categoria: "deportes", pista: "Estrella brasileña famosa por su regate y jogo bonito" },
  { nombre: "Kylian Mbappé", categoria: "deportes", pista: "Goleador francés de velocidad electrizante" },
  { nombre: "Ronaldinho", categoria: "deportes", pista: "La eterna sonrisa y magia del fútbol brasileño" },
  { nombre: "Zinedine Zidane", categoria: "deportes", pista: "Mago francés del fútbol y famoso cabezazo en la final" },
  { nombre: "Lewis Hamilton", categoria: "deportes", pista: "Heptacampeón mundial británico de Fórmula 1" },
  { nombre: "Tiger Woods", categoria: "deportes", pista: "El golfista más influyente y laureado de la era moderna" },
  { nombre: "Stephen Curry", categoria: "deportes", pista: "El mejor tirador de triples de la historia de la NBA" },
  { nombre: "Nicolás Massú", categoria: "deportes", pista: "Doble medallista de oro olímpico chileno en Atenas 2004" },
  { nombre: "Fernando González", categoria: "deportes", pista: "El 'Bombardero de La Reina' con derecha demoledora" }
];
