/**
 * BASE DE DATOS DE CARTAS - CRONOLINE (300 CARTAS)
 * 
 * Estructura de cada objeto:
 * - id: Número único identificador.
 * - titulo: Nombre corto del evento.
 * - descripcion_corta: Breve explicación del suceso histórico.
 * - año: Año en que ocurrió (número entero positivo para d.C.).
 * - categoria: 'chile' | 'universal' | 'ciencia' | 'arte'
 * - dificultad: 'facil' | 'media' | 'dificil'
 */

const CATEGORIES = {
  chile: {
    name: "Historia de Chile",
    icon: "🇨🇱",
    color: "#e11d48",
    glow: "rgba(225, 29, 72, 0.4)"
  },
  universal: {
    name: "Historia Universal",
    icon: "🌍",
    color: "#2563eb",
    glow: "rgba(37, 99, 235, 0.4)"
  },
  ciencia: {
    name: "Ciencia e Inventos",
    icon: "💡",
    color: "#059669",
    glow: "rgba(5, 150, 105, 0.4)"
  },
  arte: {
    name: "Arte y Literatura",
    icon: "🎨",
    color: "#7c3aed",
    glow: "rgba(124, 58, 237, 0.4)"
  }
};

const INITIAL_CARDS = [
  // ==================== HISTORIA UNIVERSAL (75 CARTAS) ====================
  // FÁCILES (25)
  { id: 1, titulo: "Descubrimiento de América", descripcion_corta: "Cristóbal Colón llega a las costas del continente americano (Guanahani).", año: 1492, categoria: "universal", dificultad: "facil" },
  { id: 2, titulo: "Revolución Francesa", descripcion_corta: "La Toma de la Bastilla marca el inicio del colapso de la monarquía absolutista.", año: 1789, categoria: "universal", dificultad: "facil" },
  { id: 3, titulo: "Hundimiento del Titanic", descripcion_corta: "El transatlántico británico choca contra un iceberg en el norte del Atlántico.", año: 1912, categoria: "universal", dificultad: "facil" },
  { id: 4, titulo: "Inicio de la Primera Guerra Mundial", descripcion_corta: "El asesinato del archiduque Francisco Fernando en Sarajevo detona la Gran Guerra.", año: 1914, categoria: "universal", dificultad: "facil" },
  { id: 5, titulo: "Inicio de la Segunda Guerra Mundial", descripcion_corta: "La Alemania nazi invade Polonia, desatando el conflicto bélico global.", año: 1939, categoria: "universal", dificultad: "facil" },
  { id: 6, titulo: "Caída del Muro de Berlín", descripcion_corta: "La demolición del muro simboliza el colapso del bloque soviético y la unificación alemana.", año: 1989, categoria: "universal", dificultad: "facil" },
  { id: 7, titulo: "Atentado a las Torres Gemelas", descripcion_corta: "Miembros de Al Qaeda destruyen el World Trade Center en Nueva York.", año: 2001, categoria: "universal", dificultad: "facil" },
  { id: 8, titulo: "Caída del Imperio Romano de Occidente", descripcion_corta: "El último emperador romano Rómulo Augústulo es depuesto, iniciando la Edad Media.", año: 476, categoria: "universal", dificultad: "facil" },
  { id: 9, titulo: "Independencia de los Estados Unidos", descripcion_corta: "Las trece colonias declaran formalmente su separación de la corona británica.", año: 1776, categoria: "universal", dificultad: "facil" },
  { id: 10, titulo: "Lanzamiento de las bombas atómicas", descripcion_corta: "Estados Unidos bombardea Hiroshima y Nagasaki, provocando el fin de la 2ª Guerra Mundial.", año: 1945, categoria: "universal", dificultad: "facil" },
  { id: 11, titulo: "Tragedia nuclear de Chernóbil", descripcion_corta: "Explota un reactor de la planta nuclear en Ucrania, el peor accidente civil nuclear.", año: 1986, categoria: "universal", dificultad: "facil" },
  { id: 12, titulo: "Coronación de Carlomagno", descripcion_corta: "El papa León III corona al rey de los francos como Emperador del Imperio Romano Germánico.", año: 800, categoria: "universal", dificultad: "facil" },
  { id: 13, titulo: "Disolución de la Unión Soviética", descripcion_corta: "Mijaíl Gorbachov renuncia y la bandera soviética es arriada en el Kremlin, marcando el fin de la URSS.", año: 1991, categoria: "universal", dificultad: "facil" },
  { id: 14, titulo: "Fin del Apartheid en Sudáfrica", descripcion_corta: "Nelson Mandela asume como presidente en las primeras elecciones democráticas multirraciales.", año: 1994, categoria: "universal", dificultad: "facil" },
  { id: 15, titulo: "Llegada de la Peste Negra a Europa", descripcion_corta: "La plaga de peste bubónica diezma a casi la mitad de la población europea.", año: 1347, categoria: "universal", dificultad: "facil" },
  { id: 16, titulo: "Toma de Constantinopla", descripcion_corta: "El Imperio Otomano conquista la capital bizantina, marcando el fin de la Edad Media.", año: 1453, categoria: "universal", dificultad: "facil" },
  { id: 17, titulo: "Revolución Rusa", descripcion_corta: "Los bolcheviques liderados por Lenin derrocan al gobierno provisional en la Revolución de Octubre.", año: 1917, categoria: "universal", dificultad: "facil" },
  { id: 18, titulo: "Coronación de Napoleón Bonaparte", descripcion_corta: "Napoleón se corona a sí mismo como Emperador de los franceses en Notre Dame.", año: 1804, categoria: "universal", dificultad: "facil" },
  { id: 19, titulo: "Guerra de los Seis Días", descripcion_corta: "Conflicto bélico en Medio Oriente entre Israel y una coalición árabe.", año: 1967, categoria: "universal", dificultad: "facil" },
  { id: 20, titulo: "Lanzamiento del Euro como moneda física", descripcion_corta: "El euro entra en circulación física en 12 países miembros de la Unión Europea.", año: 2002, categoria: "universal", dificultad: "facil" },
  { id: 21, titulo: "Crisis de los Misiles en Cuba", descripcion_corta: "Momento de máxima tensión de la Guerra Fría por la presencia de misiles soviéticos en Cuba.", año: 1962, categoria: "universal", dificultad: "facil" },
  { id: 22, titulo: "Ascenso de Hitler al Poder", descripcion_corta: "Adolf Hitler es nombrado Canciller de Alemania, disolviendo la República de Weimar.", año: 1933, categoria: "universal", dificultad: "facil" },
  { id: 23, titulo: "Fundación de las Naciones Unidas", descripcion_corta: "51 países firman la Carta de la ONU al término de la Segunda Guerra Mundial.", año: 1945, categoria: "universal", dificultad: "facil" },
  { id: 24, titulo: "Creación del Estado de Israel", descripcion_corta: "Se declara formalmente la independencia del nuevo Estado judío al expirar el mandato británico.", año: 1948, categoria: "universal", dificultad: "facil" },
  { id: 25, titulo: "Ejecución del Rey Luis XVI", descripcion_corta: "El monarca francés es ejecutado en la guillotina tras ser acusado de traición por la Convención.", año: 1793, categoria: "universal", dificultad: "facil" },

  // MEDIAS (25)
  { id: 26, titulo: "Batalla de Waterloo", descripcion_corta: "Napoleón es derrotado definitivamente por las tropas aliadas británicas y prusianas.", año: 1815, categoria: "universal", dificultad: "media" },
  { id: 27, titulo: "Firma de la Carta Magna", descripcion_corta: "El rey Juan I de Inglaterra firma la carta que limita por primera vez los poderes reales.", año: 1215, categoria: "universal", dificultad: "media" },
  { id: 28, titulo: "Tratado de Tordesillas", descripcion_corta: "España y Portugal dividen la exploración del Nuevo Mundo mediante una línea imaginaria.", año: 1494, categoria: "universal", dificultad: "media" },
  { id: 29, titulo: "Reforma Protestante", descripcion_corta: "Martín Lutero publica sus 95 tesis en la puerta de la iglesia de Wittenberg.", año: 1517, categoria: "universal", dificultad: "media" },
  { id: 30, titulo: "Paz de Westfalia", descripcion_corta: "Se firma la paz que pone fin a la Guerra de los Treinta Años en Europa.", año: 1648, categoria: "universal", dificultad: "media" },
  { id: 31, titulo: "Inicio de la Guerra de Secesión de EE.UU.", descripcion_corta: "Conflicto armado entre los estados del norte (Unión) y los del sur (Confederación).", año: 1861, categoria: "universal", dificultad: "media" },
  { id: 32, titulo: "Construcción del Muro de Berlín", descripcion_corta: "La RDA socialista comienza a levantar el muro para detener la fuga de sus ciudadanos al oeste.", año: 1961, categoria: "universal", dificultad: "media" },
  { id: 33, titulo: "Fundación de la Cruz Roja", descripcion_corta: "Henry Dunant promueve la creación de un organismo neutral para atender a los heridos de guerra.", año: 1863, categoria: "universal", dificultad: "media" },
  { id: 34, titulo: "Cisma de Oriente", descripcion_corta: "Mutua excomunión que consuma la división definitiva entre las iglesias Católica y Ortodoxa.", año: 1054, categoria: "universal", dificultad: "media" },
  { id: 35, titulo: "Congreso de Viena", descripcion_corta: "Las potencias europeas se reúnen para rediseñar el mapa político tras la derrota de Napoleón.", año: 1815, categoria: "universal", dificultad: "media" },
  { id: 36, titulo: "Unificación de Italia", descripcion_corta: "Se proclama el Reino de Italia bajo el reinado de Víctor Manuel II.", año: 1861, categoria: "universal", dificultad: "media" },
  { id: 37, titulo: "Unificación de Alemania", descripcion_corta: "Se funda el Imperio Alemán (Segundo Reich) tras la guerra franco-prusiana.", año: 1871, categoria: "universal", dificultad: "media" },
  { id: 38, titulo: "Primera Cruzada (Toma de Jerusalén)", descripcion_corta: "Los caballeros cristianos capturan la Ciudad Santa, estableciendo los Estados Cruzados.", año: 1099, categoria: "universal", dificultad: "media" },
  { id: 39, titulo: "Marcha sobre Roma de Mussolini", descripcion_corta: "Los camisas negras avanzan hacia la capital italiana, instalando el fascismo en el poder.", año: 1922, categoria: "universal", dificultad: "media" },
  { id: 40, titulo: "Crisis del Canal de Suez", descripcion_corta: "Conflicto diplomático y militar tras la nacionalización del canal por el presidente egipcio Nasser.", año: 1956, categoria: "universal", dificultad: "media" },
  { id: 41, titulo: "Revolución Islámica en Irán", descripcion_corta: "El sah de Irán es derrocado y el ayatolá Jomeini proclama la República Islámica.", año: 1979, categoria: "universal", dificultad: "media" },
  { id: 42, titulo: "Fundación de San Petersburgo", descripcion_corta: "El zar Pedro el Grande funda la nueva capital del Imperio Ruso a orillas del mar Báltico.", año: 1703, categoria: "universal", dificultad: "media" },
  { id: 43, titulo: "Batalla de Hastings", descripcion_corta: "Los normandos liderados por Guillermo el Conquistador invaden y dominan Inglaterra.", año: 1066, categoria: "universal", dificultad: "media" },
  { id: 44, titulo: "Tratado de Utrecht", descripcion_corta: "Acuerdos que ponen fin a la Guerra de Sucesión Española, consolidando el dominio británico.", año: 1713, categoria: "universal", dificultad: "media" },
  { id: 45, titulo: "Batalla de Trafalgar", descripcion_corta: "La armada británica derrota a la flota combinada franco-española liderada por Villeneuve.", año: 1805, categoria: "universal", dificultad: "media" },
  { id: 46, titulo: "Tratado de Brest-Litovsk", descripcion_corta: "Rusia firma la paz por separado con los Imperios Centrales, saliendo de la 1ª Guerra Mundial.", año: 1918, categoria: "universal", dificultad: "media" },
  { id: 47, titulo: "Inicio de la Guerra Civil Española", descripcion_corta: "Un sector del ejército sublevado contra la Segunda República da inicio al conflicto armado.", año: 1936, categoria: "universal", dificultad: "media" },
  { id: 48, titulo: "Toma de Granada por los Reyes Católicos", descripcion_corta: "Rendición de Boabdil, poniendo fin a la Reconquista en la península ibérica.", año: 1492, categoria: "universal", dificultad: "media" },
  { id: 49, titulo: "Fundación de Nueva Ámsterdam (Nueva York)", descripcion_corta: "Colonos holandeses compran la isla de Manhattan a nativos americanos.", año: 1626, categoria: "universal", dificultad: "media" },
  { id: 50, titulo: "Batalla de Lepanto", descripcion_corta: "La Liga Santa cristiana detiene la expansión marítima otomana en el golfo de Patras.", año: 1571, categoria: "universal", dificultad: "media" },

  // DIFÍCILES (25)
  { id: 51, titulo: "Coronación de Otón I el Grande", descripcion_corta: "Otón I es coronado Emperador, fundando formalmente el Sacro Imperio Romano Germánico.", año: 962, categoria: "universal", dificultad: "dificil" },
  { id: 52, titulo: "Fundación de la dinastía Abasí", descripcion_corta: "La dinastía Abasí toma el control del califato islámico, trasladando la capital a Bagdad.", año: 750, categoria: "universal", dificultad: "dificil" },
  { id: 53, titulo: "Cisma de Occidente", descripcion_corta: "Periodo en que la Iglesia Católica tiene dos y hasta tres papas rivales simultáneamente.", año: 1378, categoria: "universal", dificultad: "dificil" },
  { id: 54, titulo: "Guerra de los Treinta Años", descripcion_corta: "La defenestración de Praga desencadena el devastador conflicto político-religioso en Europa.", año: 1618, categoria: "universal", dificultad: "dificil" },
  { id: 55, titulo: "Batalla de Poitiers", descripcion_corta: "Las tropas francas de Carlos Martel frenan el avance de las fuerzas del califato omeya.", año: 732, categoria: "universal", dificultad: "dificil" },
  { id: 56, titulo: "Inicio de la Guerra de los Cien Años", descripcion_corta: "Conflicto feudal y dinástico entre las casas reales de Inglaterra y Francia.", año: 1337, categoria: "universal", dificultad: "dificil" },
  { id: 57, titulo: "Firma del Tratado de Verdún", descripcion_corta: "Los nietos de Carlomagno dividen el Imperio Carolingio en tres partes principales.", año: 843, categoria: "universal", dificultad: "dificil" },
  { id: 58, titulo: "Inicio de la Dinastía Ming", descripcion_corta: "Zhu Yuanzhang expulsa a los mongoles de la dinastía Yuan y asume el trono en China.", año: 1368, categoria: "universal", dificultad: "dificil" },
  { id: 59, titulo: "Expulsión de los judíos de España", descripcion_corta: "Los Reyes Católicos firman el Decreto de la Alhambra ordenando el destierro hebreo.", año: 1492, categoria: "universal", dificultad: "dificil" },
  { id: 60, titulo: "Revuelta de los Bóxers en China", descripcion_corta: "Movimiento nacionalista en China contra la influencia comercial y política extranjera.", año: 1899, categoria: "universal", dificultad: "dificil" },
  { id: 61, titulo: "Inicio de la Guerra del Peloponeso", descripcion_corta: "Atenas y Esparta inician su prolongada guerra por la hegemonía griega (431 a.C., representado d.C.).", año: 431, "comentario": "Año adaptado a escala positiva por simplicidad de orden.", categoria: "universal", dificultad: "dificil" },
  { id: 62, titulo: "Coronación de Justiniano I", descripcion_corta: "El soberano inicia su reinado en el Imperio Bizantino redactando el Corpus Juris Civilis.", año: 527, categoria: "universal", dificultad: "dificil" },
  { id: 63, titulo: "Inicio de las Guerras Médicas", descripcion_corta: "Los griegos repelen la primera invasión del Imperio Persa de Darío I (490 a.C., representado d.C.).", año: 490, categoria: "universal", dificultad: "dificil" },
  { id: 64, titulo: "Firma del Tratado de Portsmouth", descripcion_corta: "Se firma el tratado de paz negociado por Roosevelt que pone fin a la guerra ruso-japonesa.", año: 1905, categoria: "universal", dificultad: "dificil" },
  { id: 65, titulo: "Inicio de la Era Meiji", descripcion_corta: "El Emperador Mutsuhito asume el poder en Japón, iniciando la modernización e industrialización.", año: 1868, categoria: "universal", dificultad: "dificil" },
  { id: 66, titulo: "Coronación de Iván el Terrible", descripcion_corta: "Iván IV de Moscovia es coronado como el primer zar de todas las Rusias.", año: 1547, categoria: "universal", dificultad: "dificil" },
  { id: 67, titulo: "Paz de Nystad", descripcion_corta: "Tratado que pone fin a la Gran Guerra del Norte, consagrando a Rusia como potencia báltica.", año: 1721, categoria: "universal", dificultad: "dificil" },
  { id: 68, titulo: "Batalla de Mohács", descripcion_corta: "El sultán Solimán el Magnífico derrota a los húngaros, expandiendo el dominio otomano.", año: 1526, categoria: "universal", dificultad: "dificil" },
  { id: 69, titulo: "Concilio de Trento", descripcion_corta: "Se convoca el concilio ecuménico que define las bases de la Contrarreforma católica.", año: 1545, categoria: "universal", dificultad: "dificil" },
  { id: 70, titulo: "Guerra de Sucesión Austriaca", descripcion_corta: "Conflicto europeo tras la ascensión de María Teresa I al trono de los Habsburgo.", año: 1740, categoria: "universal", dificultad: "dificil" },
  { id: 71, titulo: "Batalla de Austerlitz", descripcion_corta: "Napoleón Bonaparte aplasta a las fuerzas coaligadas del Imperio Ruso e Imperio Austriaco.", año: 1805, categoria: "universal", dificultad: "dificil" },
  { id: 72, titulo: "Guerra Ruso-Turca", descripcion_corta: "Conflicto que reconfiguró los Balcanes con la independencia de Bulgaria, Serbia y Rumania.", año: 1877, categoria: "universal", dificultad: "dificil" },
  { id: 73, titulo: "Inicio de la Guerra de Sucesión Española", descripcion_corta: "Conflicto tras la muerte sin descendencia del último rey Habsburgo español, Carlos II.", año: 1701, categoria: "universal", dificultad: "dificil" },
  { id: 74, titulo: "Conferencia de Berlín", descripcion_corta: "Las potencias imperialistas se reúnen para repartirse el continente africano.", año: 1884, categoria: "universal", dificultad: "dificil" },
  { id: 75, titulo: "Ejecución de Juana de Arco", descripcion_corta: "La heroína francesa es quemada en la hoguera tras un juicio inquisitorial por herejía.", año: 1431, categoria: "universal", dificultad: "dificil" },


  // ==================== HISTORIA DE CHILE (75 CARTAS) ====================
  // FÁCILES (25)
  { id: 76, titulo: "Primera Junta Nacional de Gobierno", descripcion_corta: "Los criollos convocan a cabildo abierto, iniciando la autonomía política.", año: 1810, categoria: "chile", dificultad: "facil" },
  { id: 77, titulo: "Proclamación de la Independencia", descripcion_corta: "Bernardo O'Higgins firma el acta de Independencia formal de la República en Talca.", año: 1818, categoria: "chile", dificultad: "facil" },
  { id: 78, titulo: "Gran Terremoto de Valdivia", descripcion_corta: "El sismo más destructivo e intenso registrado instrumentalmente en la historia humana.", año: 1960, categoria: "chile", dificultad: "facil" },
  { id: 79, titulo: "Rescate de los 33 mineros", descripcion_corta: "Los mineros atrapados a 700 metros en la mina San José son izados con vida.", año: 2010, categoria: "chile", dificultad: "facil" },
  { id: 80, titulo: "Golpe de Estado en Chile", descripcion_corta: "Fuerzas Armadas bombardean La Moneda, instalando una junta militar.", año: 1973, categoria: "chile", dificultad: "facil" },
  { id: 81, titulo: "Plebiscito del Sí y el No", descripcion_corta: "Chile vota de forma masiva la no continuidad de Pinochet, iniciando la transición democrática.", año: 1988, categoria: "chile", dificultad: "facil" },
  { id: 82, titulo: "Fundación de Santiago de Nueva Extremadura", descripcion_corta: "Pedro de Valdivia funda la actual capital junto al río Mapocho.", año: 1541, categoria: "chile", dificultad: "facil" },
  { id: 83, titulo: "Combate Naval de Iquique", descripcion_corta: "El capitán Arturo Prat fallece en la cubierta del monitor peruano Huáscar.", año: 1879, categoria: "chile", dificultad: "facil" },
  { id: 84, titulo: "Retorno a la Democracia", descripcion_corta: "Patricio Aylwin asume como Presidente de la República tras la dictadura militar.", año: 1990, categoria: "chile", dificultad: "facil" },
  { id: 85, titulo: "Terremoto y Maremoto 27F", descripcion_corta: "Un terremoto de magnitud 8.8 sacude el centro-sur del país seguido por un tsunami.", año: 2010, categoria: "chile", dificultad: "facil" },
  { id: 86, titulo: "Abdicación de Bernardo O'Higgins", descripcion_corta: "El Director Supremo renuncia ante el Cabildo de Santiago para evitar una guerra civil.", año: 1823, categoria: "chile", dificultad: "facil" },
  { id: 87, titulo: "Primera mujer presidenta de Chile", descripcion_corta: "Michelle Bachelet Jeria asume su primer mandato constitucional.", año: 2006, categoria: "chile", dificultad: "facil" },
  { id: 88, titulo: "Inauguración del Metro de Santiago", descripcion_corta: "El tren subterráneo realiza su viaje inaugural en la Línea 1, de San Pablo a La Moneda.", año: 1975, categoria: "chile", dificultad: "facil" },
  { id: 89, titulo: "Ley de Voto Femenino Presidencial", descripcion_corta: "El presidente Gabriel González Videla promulga la ley que otorga el voto pleno a la mujer.", año: 1949, categoria: "chile", dificultad: "facil" },
  { id: 90, titulo: "Nacionalización del Cobre", descripcion_corta: "El Congreso Nacional aprueba por unanimidad la estatización de la gran minería del cobre.", año: 1971, categoria: "chile", dificultad: "facil" },
  { id: 91, titulo: "Visita del Papa Juan Pablo II", descripcion_corta: "El sumo pontífice realiza una histórica y masiva visita pastoral en pleno régimen militar.", año: 1987, categoria: "chile", dificultad: "facil" },
  { id: 92, titulo: "Batalla de Maipú", descripcion_corta: "El general San Martín derrota al ejército realista, consolidando la independencia de Chile.", año: 1818, categoria: "chile", dificultad: "facil" },
  { id: 93, titulo: "Incorporación de Rapa Nui a Chile", descripcion_corta: "El capitán Policarpo Toro firma el acuerdo de voluntades con los jefes de la Isla de Pascua.", año: 1888, categoria: "chile", dificultad: "facil" },
  { id: 94, titulo: "Estreno de la primera película chilena", descripcion_corta: "Se proyecta el documental mudo 'Un paseo a Playa Ancha' en Valparaíso.", año: 1903, categoria: "chile", dificultad: "facil" },
  { id: 95, titulo: "Inauguración de la Torre Costanera", descripcion_corta: "Se abre el rascacielos Gran Torre Santiago, el edificio más alto de Sudamérica.", año: 2012, categoria: "chile", dificultad: "facil" },
  { id: 96, titulo: "Batalla de Chacabuco", descripcion_corta: "El Ejército Libertador de los Andes derrota al gobernador realista Casimiro Marcó del Pont.", año: 1817, categoria: "chile", dificultad: "facil" },
  { id: 97, titulo: "Fundación de Valparaíso", descripcion_corta: "Juan de Saavedra arriba a la bahía de Quintil, fundando el histórico puerto.", año: 1536, categoria: "chile", dificultad: "facil" },
  { id: 98, titulo: "Desastre de Rancagua", descripcion_corta: "Las fuerzas de Bernardo O'Higgins son rodeadas y derrotadas, iniciando la Reconquista española.", año: 1814, categoria: "chile", dificultad: "facil" },
  { id: 99, titulo: "Creación de Carabineros de Chile", descripcion_corta: "Carlos Ibáñez del Campo unifica los cuerpos policiales y de gendarmería del país.", año: 1927, categoria: "chile", dificultad: "facil" },
  { id: 100, titulo: "Aprobación del Matrimonio Igualitario", descripcion_corta: "Se promulga la ley que permite el matrimonio civil entre personas del mismo sexo.", año: 2021, categoria: "chile", dificultad: "facil" },

  // MEDIAS (25)
  { id: 101, titulo: "Fundación de la Universidad de Chile", descripcion_corta: "Bajo la dirección de Andrés Bello se crea la sucesora de la Real Universidad de San Felipe.", año: 1842, categoria: "chile", dificultad: "media" },
  { id: 102, titulo: "Promulgación de la Constitución de 1925", descripcion_corta: "La nueva carta fundamental presidencialista reemplaza al régimen parlamentario.", año: 1925, categoria: "chile", dificultad: "media" },
  { id: 103, titulo: "Promulgación de la Constitución de 1980", descripcion_corta: "Se promulga la constitución diseñada bajo la dictadura militar tras plebiscito.", año: 1980, categoria: "chile", dificultad: "media" },
  { id: 104, titulo: "Promulgación de la Constitución de 1833", descripcion_corta: "Se establece el orden autoritario conservador ideado por Diego Portales.", año: 1833, categoria: "chile", dificultad: "media" },
  { id: 105, titulo: "Matanza de la Escuela Santa María", descripcion_corta: "El ejército abre fuego contra los obreros del salitre en huelga general en Iquique.", año: 1907, categoria: "chile", dificultad: "media" },
  { id: 106, titulo: "Fundación de Concepción", descripcion_corta: "Pedro de Valdivia funda la villa en el sitio original del puerto de Penco.", año: 1550, categoria: "chile", dificultad: "media" },
  { id: 107, titulo: "Fundación de La Serena", descripcion_corta: "Juan Bohón funda la segunda ciudad más antigua del territorio chileno.", año: 1544, categoria: "chile", dificultad: "media" },
  { id: 108, titulo: "Fundación de Valdivia", descripcion_corta: "Pedro de Valdivia funda la ciudad en el sur para consolidar el control hispano.", año: 1552, categoria: "chile", dificultad: "media" },
  { id: 109, titulo: "Inauguración del Ferrocarril Copiapó-Caldera", descripcion_corta: "Primer ferrocarril de Chile y uno de los primeros en Sudamérica, impulsado por Wheelwright.", año: 1851, categoria: "chile", dificultad: "media" },
  { id: 110, titulo: "Inauguración del Viaducto del Malleco", descripcion_corta: "Obra maestra de ingeniería vial en acero, puente ferroviario en La Araucanía.", año: 1890, categoria: "chile", dificultad: "media" },
  { id: 111, titulo: "Creación de la CORFO", descripcion_corta: "Corporación de Fomento para industrializar el país tras el terremoto de Chillán.", año: 1939, categoria: "chile", dificultad: "media" },
  { id: 112, titulo: "Terremoto de Chillán de 1939", descripcion_corta: "El terremoto con mayor número de fallecidos confirmados en la historia nacional.", año: 1939, categoria: "chile", dificultad: "media" },
  { id: 113, titulo: "Guerra Civil de 1891", descripcion_corta: "El congreso y la armada se sublevan contra el presidente Balmaceda, quien termina suicidándose.", año: 1891, categoria: "chile", dificultad: "media" },
  { id: 114, titulo: "Promulgación del Código Civil", descripcion_corta: "Redactado por Andrés Bello, entra en vigencia y define la propiedad y las personas.", año: 1855, categoria: "chile", dificultad: "media" },
  { id: 115, titulo: "Creación de la Fuerza Aérea (FACh)", descripcion_corta: "Arturo Merino Benítez funda la fuerza aérea nacional como rama independiente.", año: 1930, categoria: "chile", dificultad: "media" },
  { id: 116, titulo: "Nacionalización de la Universidad Técnica del Estado", descripcion_corta: "Se unifican las escuelas politécnicas y mineras en una sola universidad estatal (UTE).", año: 1947, categoria: "chile", dificultad: "media" },
  { id: 117, titulo: "Toma de posesión del Estrecho de Magallanes", descripcion_corta: "La goleta Ancud toma posesión soberana del estrecho construyendo el Fuerte Bulnes.", año: 1843, categoria: "chile", dificultad: "media" },
  { id: 118, titulo: "Fundación de la Universidad de Concepción", descripcion_corta: "Se crea la primera universidad privada del sur de Chile por iniciativa local.", año: 1919, categoria: "chile", dificultad: "media" },
  { id: 119, titulo: "Incendio de la Iglesia de la Compañía", descripcion_corta: "Más de 2000 personas mueren asfixiadas en el peor incendio urbano de la capital.", año: 1863, categoria: "chile", dificultad: "media" },
  { id: 120, titulo: "Ley de Instrucción Primaria Obligatoria", descripcion_corta: "Se promulga la ley que garantiza la educación primaria obligatoria y gratuita.", año: 1920, categoria: "chile", dificultad: "media" },
  { id: 121, titulo: "Firma del Tratado de Paz con Bolivia", descripcion_corta: "Se sella la paz y los límites definitivos tras la Guerra del Pacífico.", año: 1904, categoria: "chile", dificultad: "media" },
  { id: 122, titulo: "Tratado de Lima con Perú", descripcion_corta: "Tratado que resuelve la soberanía de Tacna (Perú) y Arica (Chile).", año: 1929, categoria: "chile", dificultad: "media" },
  { id: 123, titulo: "Combate de La Concepción", descripcion_corta: "Setenta y siete soldados chilenos resisten hasta la muerte contra fuerzas peruanas.", año: 1882, categoria: "chile", dificultad: "media" },
  { id: 124, titulo: "Fundación del Banco Estado", descripcion_corta: "Se fusionan cajas de ahorro público creándose el principal banco comercial del Estado.", año: 1953, categoria: "chile", dificultad: "media" },
  { id: 125, titulo: "Creación de la Región de Los Ríos", descripcion_corta: "Se promulga la ley que divide la provincia de Valdivia de la Región de Los Lagos.", año: 2007, categoria: "chile", dificultad: "media" },

  // DIFÍCILES (25)
  { id: 126, titulo: "Batalla de Lircay", descripcion_corta: "Tropas de Joaquín Prieto derrotan a Ramón Freire, iniciando la República Conservadora.", año: 1830, categoria: "chile", dificultad: "dificil" },
  { id: 127, titulo: "Combate de Papudo", descripcion_corta: "La corbeta Esmeralda captura a la goleta española Covadonga en la guerra contra España.", año: 1865, categoria: "chile", dificultad: "dificil" },
  { id: 128, titulo: "Bombardeo de Valparaíso", descripcion_corta: "La escuadra española bombardea la ciudad puerto desarmada durante tres horas.", año: 1866, categoria: "chile", dificultad: "dificil" },
  { id: 129, titulo: "Batalla de Yungay", descripcion_corta: "Las tropas chilenas de Bulnes derrotan al protector Andrés de Santa Cruz, disolviendo la Confederación.", año: 1839, categoria: "chile", dificultad: "dificil" },
  { id: 130, titulo: "Revolución Civil de 1851", descripcion_corta: "Sublevación contra el electo Manuel Montt que termina en la batalla de Loncomilla.", año: 1851, categoria: "chile", dificultad: "dificil" },
  { id: 131, titulo: "Revolución Civil de 1859", descripcion_corta: "Sublevación liberal del norte de Chile (Atacama) en contra del gobierno conservador.", año: 1859, categoria: "chile", dificultad: "dificil" },
  { id: 132, titulo: "Terremoto Magno de Santiago", descripcion_corta: "El sismo destruye la capital colonial y da origen a la leyenda del Cristo de Mayo.", año: 1647, categoria: "chile", dificultad: "dificil" },
  { id: 133, titulo: "Inauguración de Cerro Tololo", descripcion_corta: "Comienza a operar el primer observatorio científico internacional en el Valle del Elqui.", año: 1967, categoria: "chile", dificultad: "dificil" },
  { id: 134, titulo: "Inauguración de la Central Rapel", descripcion_corta: "Primera gran central hidroeléctrica de embalse del país, en la región de O'Higgins.", año: 1968, categoria: "chile", dificultad: "dificil" },
  { id: 135, titulo: "Creación de FONASA", descripcion_corta: "Fondo Nacional de Salud, creado para centralizar la recaudación médica previsional.", año: 1979, categoria: "chile", dificultad: "dificil" },
  { id: 136, titulo: "Tratado de Paz con Argentina", descripcion_corta: "Se firma bajo mediación del Papa el tratado de paz por el diferendo austral del Beagle.", año: 1984, categoria: "chile", dificultad: "dificil" },
  { id: 137, titulo: "Ingreso de Chile a la APEC", descripcion_corta: "Chile es aceptado formalmente en el foro de cooperación económica de Asia-Pacífico.", año: 1994, categoria: "chile", dificultad: "dificil" },
  { id: 138, titulo: "Entrada en vigencia del TLC con EE.UU.", descripcion_corta: "Comienza a regir el acuerdo comercial bilateral, eliminando la mayoría de aranceles.", año: 2004, categoria: "chile", dificultad: "dificil" },
  { id: 139, titulo: "Creación del Ministerio de Cultura", descripcion_corta: "Se promulga la ley que crea el Ministerio de las Culturas, las Artes y el Patrimonio.", año: 2018, categoria: "chile", dificultad: "dificil" },
  { id: 140, titulo: "Batalla de Rancagua (Sitio de Rancagua)", descripcion_corta: "Se concreta el cerco militar de Bernardo O'Higgins en la plaza central de la ciudad.", año: 1814, categoria: "chile", dificultad: "dificil" },
  { id: 141, titulo: "Creación del primer Parque Nacional", descripcion_corta: "Se declara la reserva forestal de Malleco (Parque Nacional Benjamín Vicuña Mackenna).", año: 1907, categoria: "chile", dificultad: "dificil" },
  { id: 142, titulo: "Inicio de la Guerra contra la Confederación", descripcion_corta: "El ministro Diego Portales declara la guerra por la disputa de hegemonía portuaria en el Pacífico.", año: 1836, categoria: "chile", dificultad: "dificil" },
  { id: 143, titulo: "Asesinato de Diego Portales", descripcion_corta: "El ministro es fusilado por oficiales sublevados en los cerros de Valparaíso (Barón).", año: 1837, categoria: "chile", dificultad: "dificil" },
  { id: 144, titulo: "Primer Censo Nacional Oficial", descripcion_corta: "La Oficina de Estadística efectúa el primer empadronamiento general de la población.", año: 1835, categoria: "chile", dificultad: "dificil" },
  { id: 145, titulo: "Fundación de la Academia de Pintura", descripcion_corta: "Dirigida por el artista italiano Alejandro Ciccarelli, impulsando las bellas artes en el país.", año: 1849, categoria: "chile", dificultad: "dificil" },
  { id: 146, titulo: "Establecimiento del Estanco del Tabaco", descripcion_corta: "Se entrega el monopolio de licores, naipes y té a la firma Portales, Cea y Cía.", año: 1824, categoria: "chile", dificultad: "dificil" },
  { id: 147, titulo: "Creación de la Escuadra Nacional", descripcion_corta: "Zarpa desde Valparaíso la primera flota naval de Chile bajo el mando de Blanco Encalada.", año: 1818, categoria: "chile", dificultad: "dificil" },
  { id: 148, titulo: "Descubrimiento del yacimiento de Chañarcillo", descripcion_corta: "Juan Godoy descubre el rico mineral de plata en la región de Atacama.", año: 1832, categoria: "chile", dificultad: "dificil" },
  { id: 149, titulo: "Terremoto de Chillán de 1835", descripcion_corta: "Destruye completamente la ciudad de Concepción y Chillán, presenciado por Charles Darwin.", año: 1835, categoria: "chile", dificultad: "dificil" },
  { id: 150, titulo: "Firma del Tratado de Límites con Bolivia", descripcion_corta: "Chile y Bolivia firman el primer tratado que fija la frontera en el paralelo 24 latitud sur.", año: 1866, categoria: "chile", dificultad: "dificil" },


  // ==================== CIENCIA Y TECNOLOGÍA (75 CARTAS) ====================
  // FÁCILES (25)
  { id: 151, titulo: "Llegada del Ser Humano a la Luna", descripcion_corta: "La tripulación del Apolo 11 realiza el primer alunizaje y caminata espacial en suelo lunar.", año: 1969, categoria: "ciencia", dificultad: "facil" },
  { id: 152, titulo: "Lanzamiento del Sputnik 1", descripcion_corta: "La Unión Soviética pone en órbita el primer satélite artificial, abriendo la era espacial.", año: 1957, categoria: "ciencia", dificultad: "facil" },
  { id: 153, titulo: "Invención de la Imprenta", descripcion_corta: "Johannes Gutenberg perfecciona la prensa de tipos móviles de metal en Europa.", año: 1440, categoria: "ciencia", dificultad: "facil" },
  { id: 154, titulo: "Descubrimiento de la Penicilina", descripcion_corta: "Alexander Fleming descubre el primer antibiótico de uso masivo tras notar moho en placas.", año: 1928, categoria: "ciencia", dificultad: "facil" },
  { id: 155, titulo: "Invención del Teléfono", descripcion_corta: "Alexander Graham Bell patenta el primer dispositivo eléctrico de comunicación oral a distancia.", año: 1876, categoria: "ciencia", dificultad: "facil" },
  { id: 156, titulo: "Invención de la Bombilla", descripcion_corta: "Thomas Alva Edison patenta la bombilla eléctrica de filamento de carbono comercializable.", año: 1879, categoria: "ciencia", dificultad: "facil" },
  { id: 157, titulo: "Máquina de Vapor de James Watt", descripcion_corta: "Watt patenta su versión mejorada con condensador separado, detonando la Revolución Industrial.", año: 1769, categoria: "ciencia", dificultad: "facil" },
  { id: 158, titulo: "Descubrimiento del ADN de Doble Hélice", descripcion_corta: "Watson, Crick y Franklin determinan la estructura molecular tridimensional de la vida.", año: 1953, categoria: "ciencia", dificultad: "facil" },
  { id: 159, titulo: "Invención del Automóvil Moderno", descripcion_corta: "Karl Benz patenta el primer vehículo autopropulsado por un motor de combustión interna.", año: 1886, categoria: "ciencia", dificultad: "facil" },
  { id: 160, titulo: "Primer Vuelo en Avión Controlado", descripcion_corta: "Los hermanos Wright realizan vuelos propulsados a motor en Kitty Hawk.", año: 1903, categoria: "ciencia", dificultad: "facil" },
  { id: 161, titulo: "Lanzamiento del iPhone", descripcion_corta: "Steve Jobs presenta el teléfono inteligente que popularizó las pantallas táctiles multipunto.", año: 2007, categoria: "ciencia", dificultad: "facil" },
  { id: 162, titulo: "Primer viaje espacial tripulado", descripcion_corta: "El cosmonauta soviético Yuri Gagarin completa una órbita terrestre a bordo de la nave Vostok 1.", año: 1961, categoria: "ciencia", dificultad: "facil" },
  { id: 163, titulo: "Clonación de la Oveja Dolly", descripcion_corta: "Primer mamífero clonado a partir de una célula adulta en el Instituto Roslin.", año: 1996, categoria: "ciencia", dificultad: "facil" },
  { id: 164, titulo: "Creación del World Wide Web (WWW)", descripcion_corta: "Tim Berners-Lee propone la arquitectura de hipertexto para la transferencia de información global.", año: 1889, "comentario": "Propuesto formalmente en 1989.", año: 1989, categoria: "ciencia", dificultad: "facil" },
  { id: 165, titulo: "Lanzamiento de Wikipedia", descripcion_corta: "Jimmy Wales y Larry Sanger lanzan el proyecto de enciclopedia libre editable.", año: 2001, categoria: "ciencia", dificultad: "facil" },
  { id: 166, titulo: "Lanzamiento del Telescopio Hubble", descripcion_corta: "El transbordador Discovery pone en órbita el observatorio astronómico espacial pionero.", año: 1990, categoria: "ciencia", dificultad: "facil" },
  { id: 167, titulo: "Secuenciación completa del Genoma Humano", descripcion_corta: "El consorcio internacional anuncia el mapa completo de los genes humanos.", año: 2003, categoria: "ciencia", dificultad: "facil" },
  { id: 168, titulo: "Invención del Cinematógrafo", descripcion_corta: "Los hermanos Lumière patentan el proyector y cámara, efectuando la primera función de cine.", año: 1895, categoria: "ciencia", dificultad: "facil" },
  { id: 169, titulo: "Lanzamiento de la sonda Voyager 1", descripcion_corta: "La sonda espacial de la NASA emprende su viaje hacia el espacio exterior y exterior interestelar.", año: 1977, categoria: "ciencia", dificultad: "facil" },
  { id: 170, titulo: "Invención de la Vacuna contra la Rabia", descripcion_corta: "Louis Pasteur aplica con éxito su vacuna de virus atenuado en el niño Joseph Meister.", año: 1885, categoria: "ciencia", dificultad: "facil" },
  { id: 171, titulo: "Descubrimiento de la Ley de Gravedad", descripcion_corta: "Isaac Newton formula la gravitación universal y las leyes de movimiento en los 'Principia'.", año: 1687, categoria: "ciencia", dificultad: "facil" },
  { id: 172, titulo: "Publicación de la Teoría de la Relatividad General", descripcion_corta: "Albert Einstein postula que la gravedad es la curvatura del espacio-tiempo.", año: 1915, categoria: "ciencia", dificultad: "facil" },
  { id: 173, titulo: "Descubrimiento de la Radioactividad", descripcion_corta: "Henri Becquerel descubre la emisión espontánea de radiación en las sales de uranio.", año: 1896, categoria: "ciencia", dificultad: "facil" },
  { id: 174, titulo: "Invención de la Vacuna contra la Viruela", descripcion_corta: "Edward Jenner inmuniza a un niño inoculándole virus de la viruela de las vacas.", año: 1796, categoria: "ciencia", dificultad: "facil" },
  { id: 175, titulo: "Lanzamiento de la red ARPANET", descripcion_corta: "Se envía el primer mensaje por red de computadoras entre UCLA y Stanford, origen del Internet.", año: 1969, categoria: "ciencia", dificultad: "facil" },

  // MEDIAS (25)
  { id: 176, titulo: "Teoría de la Relatividad Especial", descripcion_corta: "Albert Einstein establece la equivalencia masa-energía y la velocidad constante de la luz.", año: 1905, categoria: "ciencia", dificultad: "media" },
  { id: 177, titulo: "Descubrimiento de los Rayos X", descripcion_corta: "Wilhelm Röntgen descubre una radiación invisible capaz de atravesar cuerpos opacos.", año: 1895, categoria: "ciencia", dificultad: "media" },
  { id: 178, titulo: "Invención de la Dinamita", descripcion_corta: "Alfred Nobel patenta la dinamita, estabilizando la nitroglicerina con tierra de diatomeas.", año: 1867, categoria: "ciencia", dificultad: "media" },
  { id: 179, titulo: "Primer Trasplante de Corazón Humano", descripcion_corta: "Christian Barnard lidera la histórica cirugía cardíaca en Ciudad del Cabo.", año: 1967, categoria: "ciencia", dificultad: "media" },
  { id: 180, titulo: "Descubrimiento de las Leyes de Herencia", descripcion_corta: "Gregor Mendel publica sus experimentos de hibridación en guisantes, naciendo la genética.", año: 1866, categoria: "ciencia", dificultad: "media" },
  { id: 181, titulo: "Formulación de la Tabla Periódica", descripcion_corta: "Dmitri Mendeléyev organiza los elementos químicos según su masa atómica.", año: 1869, categoria: "ciencia", dificultad: "media" },
  { id: 182, titulo: "Invención del Transistor", descripcion_corta: "Bardeen, Brattain y Shockley demuestran el primer amplificador semiconductor en Bell Labs.", año: 1947, categoria: "ciencia", dificultad: "media" },
  { id: 183, titulo: "Invención del Telégrafo Eléctrico", descripcion_corta: "Samuel Morse patenta el telégrafo e introduce el código que lleva su nombre.", año: 1837, categoria: "ciencia", dificultad: "media" },
  { id: 184, titulo: "Invención del Microprocesador", descripcion_corta: "Intel lanza el modelo 4004, integrando toda la CPU de una computadora en un chip.", año: 1971, categoria: "ciencia", dificultad: "media" },
  { id: 185, titulo: "Descubrimiento del Planeta Neptuno", descripcion_corta: "Galle observa el planeta en Berlín basándose en cálculos matemáticos de Le Verrier.", año: 1846, categoria: "ciencia", dificultad: "media" },
  { id: 186, titulo: "Descubrimiento del Planeta Urano", descripcion_corta: "William Herschel identifica el planeta usando un telescopio fabricado por él mismo.", año: 1781, categoria: "ciencia", dificultad: "media" },
  { id: 187, titulo: "Invención de la Pila Voltaica", descripcion_corta: "Alessandro Volta construye la primera batería capaz de producir corriente continua.", año: 1800, categoria: "ciencia", dificultad: "media" },
  { id: 188, titulo: "Teoría de la Deriva Continental", descripcion_corta: "Alfred Wegener propone la teoría de Pangea y la deriva continental.", año: 1912, categoria: "ciencia", dificultad: "media" },
  { id: 189, titulo: "Invención del Radar", descripcion_corta: "Robert Watson-Watt patenta el sistema de detección por ondas de radio.", año: 1935, categoria: "ciencia", dificultad: "media" },
  { id: 190, titulo: "Invención de la Computadora ENIAC", descripcion_corta: "Se presenta la primera computadora digital programable de propósito general basada en tubos.", año: 1946, categoria: "ciencia", dificultad: "media" },
  { id: 191, titulo: "Descubrimiento del Oxígeno", descripcion_corta: "Joseph Priestley y Carl Wilhelm Scheele aíslan de forma independiente el oxígeno gaseoso.", año: 1774, categoria: "ciencia", dificultad: "media" },
  { id: 192, titulo: "Teoría de la Evolución de las Especies", descripcion_corta: "Charles Darwin publica 'El origen de las especies por medio de la selección natural'.", año: 1859, categoria: "ciencia", dificultad: "media" },
  { id: 193, titulo: "Descubrimiento del electrón", descripcion_corta: "J.J. Thomson identifica la primera partícula subatómica elemental mediante rayos catódicos.", año: 1897, categoria: "ciencia", dificultad: "media" },
  { id: 194, titulo: "Descubrimiento de los Grupos Sanguíneos", descripcion_corta: "Karl Landsteiner descubre los tipos de sangre A, B y O, haciendo seguras las transfusiones.", año: 1900, categoria: "ciencia", dificultad: "media" },
  { id: 195, titulo: "Descubrimiento del Bosón de Higgs", descripcion_corta: "Científicos del Gran Colisionador de Hadrones (CERN) confirman la existencia del bosón.", año: 2012, categoria: "ciencia", dificultad: "media" },
  { id: 196, titulo: "Invención de la Fotografía (Daguerrotipo)", descripcion_corta: "Louis Daguerre presenta el primer procedimiento fotográfico comercial.", año: 1839, categoria: "ciencia", dificultad: "media" },
  { id: 197, titulo: "Formulación de las Leyes de Kepler", descripcion_corta: "Johannes Kepler publica las dos primeras leyes de las órbitas elípticas de los planetas.", año: 1609, categoria: "ciencia", dificultad: "media" },
  { id: 198, titulo: "Invención del Telescopio Refractor", descripcion_corta: "Galileo Galilei construye su telescopio y realiza las primeras observaciones lunares y de Júpiter.", año: 1609, categoria: "ciencia", dificultad: "media" },
  { id: 199, titulo: "Invención de la Máquina de Escribir", descripcion_corta: "Sholes, Glidden y Soule patentan la primera máquina práctica y comercializada.", año: 1868, categoria: "ciencia", dificultad: "media" },
  { id: 200, titulo: "Lanzamiento del Telescopio James Webb", descripcion_corta: "El telescopio infrarrojo es lanzado al espacio profundo para estudiar las galaxias.", año: 2021, categoria: "ciencia", dificultad: "media" },

  // DIFÍCILES (25)
  { id: 201, titulo: "Publicación de la teoría heliocéntrica", descripcion_corta: "Nicolás Copérnico publica 'De revolutionibus orbium coelestium', postulando el Sol en el centro.", año: 1543, categoria: "ciencia", dificultad: "dificil" },
  { id: 202, titulo: "Descubrimiento de la circulación de la sangre", descripcion_corta: "William Harvey publica su modelo sobre el funcionamiento del corazón y arterias.", año: 1628, categoria: "ciencia", dificultad: "dificil" },
  { id: 203, titulo: "Descubrimiento de las bacterias", descripcion_corta: "Anton van Leeuwenhoek observa microorganismos en muestras de agua usando microscopios domésticos.", año: 1676, categoria: "ciencia", dificultad: "dificil" },
  { id: 204, titulo: "Invención del Termómetro de Mercurio", descripcion_corta: "Daniel Gabriel Fahrenheit diseña el termómetro fiable y crea la escala de temperatura homónima.", año: 1714, categoria: "ciencia", dificultad: "dificil" },
  { id: 205, titulo: "Invención del Pararrayos", descripcion_corta: "Benjamin Franklin realiza experimentos con cometas en tormentas y patenta el invento.", año: 1752, categoria: "ciencia", dificultad: "dificil" },
  { id: 206, titulo: "Invención del Microscopio Compuesto", descripcion_corta: "Zacharias Janssen y su padre fabrican un cilindro óptico precursor del microscopio moderno.", año: 1590, categoria: "ciencia", dificultad: "dificil" },
  { id: 207, titulo: "Descubrimiento de las Células", descripcion_corta: "Robert Hooke describe cavidades en el corcho que asemejan celdas, acuñando el término celular.", año: 1665, categoria: "ciencia", dificultad: "dificil" },
  { id: 208, titulo: "Descubrimiento del neutrón", descripcion_corta: "James Chadwick demuestra la existencia del neutrón en el núcleo de los átomos.", año: 1932, categoria: "ciencia", dificultad: "dificil" },
  { id: 209, titulo: "Invención del Marcapasos Implantable", descripcion_corta: "Rune Elmqvist y Senning implantan el primer marcapasos interno permanente en Suecia.", año: 1958, categoria: "ciencia", dificultad: "dificil" },
  { id: 210, titulo: "Invención del Telescopio Reflector", descripcion_corta: "Isaac Newton inventa el telescopio newtoniano de espejos para eliminar la aberración cromática.", año: 1668, categoria: "ciencia", dificultad: "dificil" },
  { id: 211, titulo: "Primer Vuelo en Globo Aerostático", descripcion_corta: "Los hermanos Montgolfier realizan el primer vuelo tripulado por humanos en París.", año: 1783, categoria: "ciencia", dificultad: "dificil" },
  { id: 212, titulo: "Invención del Submarino Militar", descripcion_corta: "David Bushnell diseña el 'Turtle', primer sumergible autopropulsado militar.", año: 1775, categoria: "ciencia", dificultad: "dificil" },
  { id: 213, titulo: "Descubrimiento de la estructura del benceno", descripcion_corta: "August Kekulé propone la estructura cíclica de anillo plano para el benceno.", año: 1865, categoria: "ciencia", dificultad: "dificil" },
  { id: 214, titulo: "Descubrimiento de la radiación cósmica de fondo", descripcion_corta: "Penzias y Wilson detectan por accidente el eco remanente del Big Bang en una antena.", año: 1964, categoria: "ciencia", dificultad: "dificil" },
  { id: 215, titulo: "Confirmación de ondas gravitacionales", descripcion_corta: "El experimento LIGO capta vibraciones en el espacio-tiempo predichas por Einstein.", año: 2015, categoria: "ciencia", dificultad: "dificil" },
  { id: 216, titulo: "Primera foto de un agujero negro", descripcion_corta: "El telescopio Event Horizon obtiene la imagen de la silueta del agujero negro en la galaxia M87.", año: 2019, categoria: "ciencia", dificultad: "dificil" },
  { id: 217, titulo: "Aterrizaje en un Cometa (Misión Rosetta)", descripcion_corta: "La sonda Rosetta suelta el módulo Philae sobre el cometa 67P/Churiúmov-Guerasimenko.", año: 2014, categoria: "ciencia", dificultad: "dificil" },
  { id: 218, titulo: "Creación del Lenguaje Fortran", descripcion_corta: "John Backus en IBM crea el primer lenguaje de programación comercial de alto nivel.", año: 1957, categoria: "ciencia", dificultad: "dificil" },
  { id: 219, titulo: "Invención del Horno de Microondas", descripcion_corta: "Percy Spencer descubre el calentamiento provocado por magnetrones de radar comerciales.", año: 1945, categoria: "ciencia", dificultad: "dificil" },
  { id: 220, titulo: "Primer Reactor Nuclear Autocontrolado", descripcion_corta: "Enrico Fermi dirige la pila atómica Chicago Pile-1, iniciando la era nuclear controlada.", año: 1942, categoria: "ciencia", dificultad: "dificil" },
  { id: 221, titulo: "Invención del Motor Diésel", descripcion_corta: "Rudolf Diesel patenta y prueba el primer motor de encendido por compresión eficiente.", año: 1897, categoria: "ciencia", dificultad: "dificil" },
  { id: 222, titulo: "Invención de la Desmotadora de Algodón", descripcion_corta: "Eli Whitney revoluciona la agricultura estadounidense con su desmotadora mecánica.", año: 1793, categoria: "ciencia", dificultad: "dificil" },
  { id: 223, titulo: "Invención del Plástico Sintético (Baquelita)", descripcion_corta: "Leo Baekeland patenta la resina sintética termoestable, naciendo la era plástica.", año: 1907, categoria: "ciencia", dificultad: "dificil" },
  { id: 224, titulo: "Descubrimiento de la Anomalía de Urano", descripcion_corta: "Alexis Bouvard publica tablas astronómicas con discrepancias que implican un octavo planeta.", año: 1821, categoria: "ciencia", dificultad: "dificil" },
  { id: 225, titulo: "Invención de la cosechadora mecánica", descripcion_corta: "Cyrus McCormick diseña y patenta la segadora-cosechadora de cereales en Virginia.", año: 1831, categoria: "ciencia", dificultad: "dificil" },


  // ==================== ARTE Y LITERATURA (75 CARTAS) ====================
  // FÁCILES (25)
  { id: 226, titulo: "Publicación de Don Quijote de la Mancha", descripcion_corta: "Miguel de Cervantes Saavedra publica la primera parte de su célebre novela caballeresca.", año: 1605, categoria: "arte", dificultad: "facil" },
  { id: 227, titulo: "Pintura de la Mona Lisa (La Gioconda)", descripcion_corta: "Leonardo da Vinci inicia la obra pictórica en el Renacimiento italiano.", año: 1503, categoria: "arte", dificultad: "facil" },
  { id: 228, titulo: "Gabriela Mistral recibe el Nobel", descripcion_corta: "La escritora chilena es galardonada con el Premio Nobel de Literatura.", año: 1945, categoria: "arte", dificultad: "facil" },
  { id: 229, titulo: "Pablo Neruda recibe el Nobel", descripcion_corta: "El poeta e intelectual chileno obtiene la consagración con el Premio Nobel.", año: 1971, categoria: "arte", dificultad: "facil" },
  { id: 230, titulo: "Inauguración de la Torre Eiffel", descripcion_corta: "La estructura de hierro forjado es inaugurada para la Exposición Universal en París.", año: 1889, categoria: "arte", dificultad: "facil" },
  { id: 231, titulo: "Pintura del Guernica", descripcion_corta: "Pablo Picasso inmortaliza el bombardeo nazi sobre la localidad vizcaína en su mural cubista.", año: 1937, categoria: "arte", dificultad: "facil" },
  { id: 232, titulo: "Estreno de la Novena Sinfonía de Beethoven", descripcion_corta: "Se presenta en Viena, incluyendo la innovadora parte coral de la 'Oda a la alegría'.", año: 1824, categoria: "arte", dificultad: "facil" },
  { id: 233, titulo: "Pintura de 'La Noche Estrellada'", descripcion_corta: "Vincent van Gogh pinta su emblemático lienzo azul y amarillo desde el asilo de Saint-Rémy.", año: 1889, categoria: "arte", dificultad: "facil" },
  { id: 234, titulo: "Pintura de 'El Grito'", descripcion_corta: "Edvard Munch retrata la angustia existencial humana en el movimiento expresionista.", año: 1893, categoria: "arte", dificultad: "facil" },
  { id: 235, titulo: "Publicación de 'El Principito'", descripcion_corta: "El novelista y aviador Antoine de Saint-Exupéry edita su célebre libro de reflexiones infantiles.", año: 1943, categoria: "arte", dificultad: "facil" },
  { id: 236, titulo: "Estreno de 'Hamlet' de Shakespeare", descripcion_corta: "Se publica y representa la inmortal obra trágica del bardo inglés.", año: 1603, categoria: "arte", dificultad: "facil" },
  { id: 237, titulo: "Terminación de 'El David'", descripcion_corta: "Miguel Ángel esculpe el soberbio gigante de mármol blanco de Carrara en Florencia.", año: 1504, categoria: "arte", dificultad: "facil" },
  { id: 238, titulo: "Frescos del Techo de la Capilla Sixtina", descripcion_corta: "Miguel Ángel culmina la pintura mural encargada por el Papa Julio II en Roma.", año: 1512, categoria: "arte", dificultad: "facil" },
  { id: 239, titulo: "Publicación de 'Cien años de soledad'", descripcion_corta: "Gabriel García Márquez publica su obra cumbre del realismo mágico en Buenos Aires.", año: 1967, categoria: "arte", dificultad: "facil" },
  { id: 240, titulo: "Pintura de 'Las Meninas'", descripcion_corta: "Diego Velázquez retrata a la infanta Margarita rodeada de su corte en el palacio real.", año: 1656, categoria: "arte", dificultad: "facil" },
  { id: 241, titulo: "Publicación de '1984'", descripcion_corta: "George Orwell edita su novela distópica sobre el Gran Hermano y la manipulación social.", año: 1949, categoria: "arte", dificultad: "facil" },
  { id: 242, titulo: "Publicación de 'El Hobbit'", descripcion_corta: "J.R.R. Tolkien lanza su novela fantástica, precursora de El Señor de los Anillos.", año: 1937, categoria: "arte", dificultad: "facil" },
  { id: 243, titulo: "Publicación de 'Romeo y Julieta'", descripcion_corta: "Shakespeare estrena la tragedia romántica de los amantes desdichados de Verona.", año: 1597, categoria: "arte", dificultad: "facil" },
  { id: 244, titulo: "Publicación de 'Frankenstein'", descripcion_corta: "Mary Shelley lanza su novela gótica y pionera de la ciencia ficción, escrita en Villa Diodati.", año: 1818, categoria: "arte", dificultad: "facil" },
  { id: 245, titulo: "Estreno de 'Tiempos Modernos' de Chaplin", descripcion_corta: "Se estrena el filme mudo que retrata con humor la mecanización industrial.", año: 1936, categoria: "arte", dificultad: "facil" },
  { id: 246, titulo: "Estreno de la película 'Star Wars'", descripcion_corta: "George Lucas estrena el Episodio IV, dando origen a la saga multimillonaria de ópera espacial.", año: 1977, categoria: "arte", dificultad: "facil" },
  { id: 247, titulo: "Inauguración de la Ópera de Sídney", descripcion_corta: "Se inaugura el icónico edificio diseñado por Jørn Utzon en Australia.", año: 1973, categoria: "arte", dificultad: "facil" },
  { id: 248, titulo: "Publicación de 'Drácula'", descripcion_corta: "Bram Stoker publica su novela epistolar, consagrando el mito del vampiro moderno.", año: 1897, categoria: "arte", dificultad: "facil" },
  { id: 249, titulo: "Estreno de 'El Ciudadano Kane'", descripcion_corta: "Orson Welles dirige y protagoniza la influyente película sobre la vida de un magnate.", año: 1941, categoria: "arte", dificultad: "facil" },
  { id: 250, titulo: "Estreno de 'La flauta mágica' de Mozart", descripcion_corta: "Se presenta en Viena el *Singspiel* operístico, semanas antes del fallecimiento del compositor.", año: 1791, categoria: "arte", dificultad: "facil" },

  // MEDIAS (25)
  { id: 251, titulo: "La Divina Comedia (Dante Alighieri)", descripcion_corta: "Se completa el viaje poético a través del Infierno, Purgatorio y Paraíso.", año: 1320, categoria: "arte", dificultad: "media" },
  { id: 252, titulo: "Pintura de 'El Nacimiento de Venus'", descripcion_corta: "Sandro Botticelli plasma a la diosa emergiendo de las aguas sobre una concha.", año: 1485, categoria: "arte", dificultad: "media" },
  { id: 253, titulo: "Estreno de 'El lago de los cisnes'", descripcion_corta: "El ballet con música de Piotr Ilich Tchaikovsky se estrena en el Teatro Bolshói.", año: 1877, categoria: "arte", dificultad: "media" },
  { id: 254, titulo: "Estreno de la ópera 'La Traviata'", descripcion_corta: "Giuseppe Verdi estrena su ópera basada en la novela de La dama de las camelias.", año: 1853, categoria: "arte", dificultad: "media" },
  { id: 255, titulo: "Publicación de 'El Gran Gatsby'", descripcion_corta: "F. Scott Fitzgerald publica la novela sobre la decadencia del sueño americano en los años veinte.", año: 1925, categoria: "arte", dificultad: "media" },
  { id: 256, titulo: "Publicación de 'La Metamorfosis'", descripcion_corta: "Franz Kafka edita su relato sobre la transformación de Gregorio Samsa.", año: 1915, categoria: "arte", dificultad: "media" },
  { id: 257, titulo: "Publicación de 'Ulises' de James Joyce", descripcion_corta: "La controvertida y monumental novela modernista se edita íntegramente en París.", año: 1922, categoria: "arte", dificultad: "media" },
  { id: 258, titulo: "Estreno de 'Carmen' de Georges Bizet", descripcion_corta: "La ópera que escandalizó al público por su temática gitana se estrena en París.", año: 1875, categoria: "arte", dificultad: "media" },
  { id: 259, titulo: "Publicación de 'Los Miserables'", descripcion_corta: "Victor Hugo publica su célebre crítica social de la Francia de inicios del siglo XIX.", año: 1862, categoria: "arte", dificultad: "media" },
  { id: 260, titulo: "Publicación de 'Crimen y castigo'", descripcion_corta: "Fiódor Dostoievski lanza en folletines la historia de culpa y redención de Raskólnikov.", año: 1866, categoria: "arte", dificultad: "media" },
  { id: 261, titulo: "Publicación de 'Guerra y paz'", descripcion_corta: "Lev Tolstói completa la crónica de la invasión napoleónica a Rusia en su novela.", año: 1869, categoria: "arte", dificultad: "media" },
  { id: 262, titulo: "Pintura de 'La Última Cena'", descripcion_corta: "Leonardo da Vinci culmina la obra mural sobre los apóstoles en Milán.", año: 1498, categoria: "arte", dificultad: "media" },
  { id: 263, titulo: "Pintura de 'La Escuela de Atenas'", descripcion_corta: "Rafael Sanzio representa a los filósofos clásicos en un mural en los palacios vaticanos.", año: 1511, categoria: "arte", dificultad: "media" },
  { id: 264, titulo: "Pintura de 'El Jardín de las Delicias'", descripcion_corta: "El Bosco pinta su críptico y asombroso tríptico al óleo sobre madera.", año: 1500, categoria: "arte", dificultad: "media" },
  { id: 265, titulo: "Estreno de la Quinta Sinfonía de Beethoven", descripcion_corta: "Se presenta con sus icónicos y enérgicos cuatro acordes iniciales en Viena.", año: 1808, categoria: "arte", dificultad: "media" },
  { id: 266, titulo: "Estreno del Mesías de Händel", descripcion_corta: "El oratorio barroco en inglés se estrena en un concierto benéfico en Dublín.", año: 1742, categoria: "arte", dificultad: "media" },
  { id: 267, titulo: "Estreno de 'Don Giovanni' de Mozart", descripcion_corta: "La ópera cómica dramática basada en la leyenda de Don Juan se presenta en Praga.", año: 1787, categoria: "arte", dificultad: "media" },
  { id: 268, titulo: "Estreno del ballet 'El Cascanueces'", descripcion_corta: "Se estrena la obra navideña con música de Tchaikovsky en San Petersburgo.", año: 1892, categoria: "arte", dificultad: "media" },
  { id: 269, titulo: "Publicación de 'Fausto' de Goethe", descripcion_corta: "Se publica la primera parte del drama filosófico sobre el pacto con Mefistófeles.", año: 1808, categoria: "arte", dificultad: "media" },
  { id: 270, titulo: "Publicación de 'El paraíso perdido'", descripcion_corta: "John Milton escribe su poema épico de caída humana y rebelión de Lucifer.", año: 1667, categoria: "arte", dificultad: "media" },
  { id: 271, titulo: "Publicación de 'Ficciones' de Borges", descripcion_corta: "El célebre volumen de cuentos laberínticos e intelectuales se edita en Buenos Aires.", año: 1944, categoria: "arte", dificultad: "media" },
  { id: 272, titulo: "Publicación de 'Pedro Páramo'", descripcion_corta: "El escritor mexicano Juan Rulfo publica su novela corta ambientada en Comala.", año: 1955, categoria: "arte", dificultad: "media" },
  { id: 273, titulo: "Estreno de 'Metrópolis' de Fritz Lang", descripcion_corta: "Se proyecta el pionero largometraje expresionista alemán de ciencia ficción.", año: 1927, categoria: "arte", dificultad: "media" },
  { id: 274, titulo: "Estreno de 'Casablanca'", descripcion_corta: "Se estrena el clásico dramático y romántico bélico protagonizado por Bogart e Bergman.", año: 1942, categoria: "arte", dificultad: "media" },
  { id: 275, titulo: "Estreno de '2001: Odisea del Espacio'", descripcion_corta: "Se estrena la obra maestra cinematográfica de ciencia ficción de Stanley Kubrick.", año: 1968, categoria: "arte", dificultad: "media" },

  // DIFÍCILES (25)
  { id: 276, titulo: "Publicación del manuscrito de Cantar de Mío Cid", descripcion_corta: "Se registra la copia conservada del poema épico del caballero castellano.", año: 1207,  categoria: "arte", dificultad: "dificil" },
  { id: 277, titulo: "Publicación de 'Los tres mosqueteros'", descripcion_corta: "Alexandre Dumas publica por entregas las aventuras de D'Artagnan en París.", año: 1844, categoria: "arte", dificultad: "dificil" },
  { id: 278, titulo: "Publicación de 'Moby Dick'", descripcion_corta: "Herman Melville edita su novela de la trágica obsesión del capitán Ahab por la ballena blanca.", año: 1851, categoria: "arte", dificultad: "dificil" },
  { id: 279, titulo: "Publicación de 'Alicia en el país de las maravillas'", descripcion_corta: "Lewis Carroll publica su clásica obra satírica del sinsentido.", año: 1865, categoria: "arte", dificultad: "dificil" },
  { id: 280, titulo: "Publicación de 'La isla del tesoro'", descripcion_corta: "Robert Louis Stevenson lanza la gran novela de piratas y tesoros enterrados.", año: 1883, categoria: "arte", dificultad: "dificil" },
  { id: 281, titulo: "Publicación de 'La guerra de los mundos'", descripcion_corta: "H.G. Wells imagina la invasión marciana a la Tierra en su novela de ciencia ficción.", año: 1898, categoria: "arte", dificultad: "dificil" },
  { id: 282, titulo: "Estreno de 'El nacimiento de una nación'", descripcion_corta: "La polémica pero técnicamente innovadora película muda de D.W. Griffith se estrena en EE.UU.", año: 1915, categoria: "arte", dificultad: "dificil" },
  { id: 283, titulo: "Estreno de 'El Acorazado Potemkin'", descripcion_corta: "Serguéi Eisenstein dirige el filme mudo soviético con la famosa escena de las escaleras de Odesa.", año: 1925, categoria: "arte", dificultad: "dificil" },
  { id: 284, titulo: "Estreno de la película 'El Mago de Oz'", descripcion_corta: "Victor Fleming estrena el filme musical de fantasía que popularizó el Technicolor.", año: 1939, categoria: "arte", dificultad: "dificil" },
  { id: 285, titulo: "Estreno de 'Lo que el viento se llevó'", descripcion_corta: "El gigantesco drama histórico y romántico sobre la Guerra Civil estadounidense se estrena en Atlanta.", año: 1939, categoria: "arte", dificultad: "dificil" },
  { id: 286, titulo: "Estreno de 'Cantando bajo la lluvia'", descripcion_corta: "Gene Kelly y Stanley Donen dirigen y protagonizan el aclamado filme musical hollywoodense.", año: 1952, categoria: "arte", dificultad: "dificil" },
  { id: 287, titulo: "Escultura de 'El Éxtasis de Santa Teresa'", descripcion_corta: "Gian Lorenzo Bernini culmina el grupo escultórico barroco en mármol en Roma.", año: 1652, categoria: "arte", dificultad: "dificil" },
  { id: 288, titulo: "Estreno de la Sinfonía N.º 40 de Mozart", descripcion_corta: "Mozart compone y estrena la que sería una de sus sinfonías más famosas en Sol menor.", año: 1788, categoria: "arte", dificultad: "dificil" },
  { id: 289, titulo: "Publicación de 'En busca del tiempo perdido'", descripcion_corta: "Marcel Proust publica 'Por el camino de Swann', primer volumen de su magna novela.", año: 1913, categoria: "arte", dificultad: "dificil" },
  { id: 290, titulo: "Publicación de 'La tierra baldía'", descripcion_corta: "T.S. Eliot publica su influyente poema de la desolación de posguerra.", año: 1922, categoria: "arte", dificultad: "dificil" },
  { id: 291, titulo: "Publicación de 'El Aleph'", descripcion_corta: "Jorge Luis Borges publica la compilación de cuentos de corte fantástico.", año: 1949, categoria: "arte", dificultad: "dificil" },
  { id: 292, titulo: "Primera Exhibición Impresionista", descripcion_corta: "Monet, Renoir, Degas y otros exponen en el taller del fotógrafo Nadar en París.", año: 1874, categoria: "arte", dificultad: "dificil" },
  { id: 293, titulo: "Estreno de 'La consagración de la primavera'", descripcion_corta: "Igor Stravinsky provoca un tumulto escandaloso por su rítmica y coreografía en París.", año: 1913, categoria: "arte", dificultad: "dificil" },
  { id: 294, titulo: "Estreno del 'Bolero' de Maurice Ravel", descripcion_corta: "Se presenta la obra orquestal de crescendo continuo en la Ópera de París.", año: 1928, categoria: "arte", dificultad: "dificil" },
  { id: 295, titulo: "Publicación de 'Las Flores del Mal'", descripcion_corta: "Charles Baudelaire publica el poemario simbolista, sufriendo censura por inmoralidad.", año: 1857, categoria: "arte", dificultad: "dificil" },
  { id: 296, titulo: "Escultura de 'El Pensador'", descripcion_corta: "Auguste Rodin modela la icónica figura masculina absorta en profundos pensamientos.", año: 1902, "comentario": "Primer molde completo en 1902.", año: 1902, categoria: "arte", dificultad: "dificil" },
  { id: 297, titulo: "Publicación de 'Cantar de los Cantares' (Fray Luis)", descripcion_corta: "Fray Luis de León traduce del hebreo al castellano el libro bíblico, costándole la cárcel.", año: 1561, categoria: "arte", dificultad: "dificil" },
  { id: 298, titulo: "Estreno de la 'Oda a la Alegría' (Poema)", descripcion_corta: "Friedrich Schiller publica el poema que años más tarde integraría la 9ª de Beethoven.", año: 1785, categoria: "arte", dificultad: "dificil" },
  { id: 299, titulo: "Estreno de la película 'Viaje a la Luna'", descripcion_corta: "Georges Méliès estrena el filme mudo de ciencia ficción con el icónico cohete en el ojo lunar.", año: 1902, categoria: "arte", dificultad: "dificil" },
  { id: 300, titulo: "Estreno de 'Jesucristo Superstar' en Broadway", descripcion_corta: "La ópera rock con música de Andrew Lloyd Webber debuta en la escena teatral neoyorquina.", año: 1971, categoria: "arte", dificultad: "dificil" }
];
